#![forbid(unsafe_code)]

//! WP-752 generated-adapter ownership, fixture, and decomposition proofs.

use std::fs;
use std::path::{Path, PathBuf};

struct Layer {
    source: &'static str,
    generated: &'static str,
    frozen: &'static str,
}

const LAYERS: &[Layer] = &[
    Layer {
        source: "crates/riffdb-service/src/dto.rs",
        generated: "crates/riffdb-service/src/generated/dto.rs",
        frozen: "fixtures/compatibility/operation-adapters-v1/riffdb-service/dto.rs.in",
    },
    Layer {
        source: "crates/riffdb-api-grpc/src/conversion.rs",
        generated: "crates/riffdb-api-grpc/src/generated/conversion.rs",
        frozen: "fixtures/compatibility/operation-adapters-v1/riffdb-api-grpc/conversion.rs.in",
    },
    Layer {
        source: "crates/riffdb-api-mcp/src/service_backend.rs",
        generated: "crates/riffdb-api-mcp/src/generated/service_backend.rs",
        frozen: "fixtures/compatibility/operation-adapters-v1/riffdb-api-mcp/service_backend.rs.in",
    },
    Layer {
        source: "crates/riffdb-cli/src/app.rs",
        generated: "crates/riffdb-cli/src/generated/app.rs",
        frozen: "fixtures/compatibility/operation-adapters-v1/riffdb-cli/app.rs.in",
    },
    Layer {
        source: "crates/riffdb-client-rust/src/client.rs",
        generated: "crates/riffdb-client-rust/src/generated/client.rs",
        frozen: "fixtures/compatibility/operation-adapters-v1/riffdb-client-rust/client.rs.in",
    },
];

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace root")
        .to_owned()
}

fn read(root: &Path, path: &str) -> String {
    fs::read_to_string(root.join(path)).unwrap_or_else(|error| panic!("read {path}: {error}"))
}

fn generated_from_frozen(frozen: &str) -> String {
    let without_doc = frozen
        .strip_prefix("//! ")
        .and_then(|source| source.split_once('\n'))
        .map_or(frozen, |(_, source)| {
            source.strip_prefix('\n').unwrap_or(source)
        });
    let mut generated =
        String::from("// @generated by scripts/generate-operation-adapters; DO NOT EDIT.\n\n");
    generated.push_str(without_doc);
    for macro_name in ["include_str!(", "include_bytes!("] {
        let mut search_from = 0;
        while let Some(relative) = generated[search_from..].find(macro_name) {
            let macro_start = search_from + relative;
            let Some(quote_relative) = generated[macro_start..].find('"') else {
                break;
            };
            let quote = macro_start + quote_relative;
            generated.insert_str(quote + 1, "../");
            search_from = quote + 4;
        }
    }
    generated
}

#[test]
fn five_adapter_crates_contain_no_hand_written_conversion_or_dispatch() {
    let root = root();
    for layer in LAYERS {
        let source = read(&root, layer.source);
        assert!(
            source.contains("include!(\"generated/"),
            "{} regained hand-written adapter ownership",
            layer.source
        );
        assert!(
            !source.contains("fn ") && !source.contains("impl "),
            "{} contains hand-written conversion or dispatch",
            layer.source
        );
        let generated = read(&root, layer.generated);
        assert!(
            generated
                .starts_with("// @generated by scripts/generate-operation-adapters; DO NOT EDIT.")
        );
    }
}

#[test]
fn generated_adapters_reproduce_the_remaining_frozen_layers_byte_for_byte() {
    let root = root();
    for layer in LAYERS {
        let frozen = read(&root, layer.frozen);
        assert_eq!(
            read(&root, layer.generated),
            generated_from_frozen(&frozen),
            "{} drifted from its pre-generation fixture",
            layer.generated
        );
    }
}

#[test]
fn adapter_path_files_stay_under_the_decomposition_budget() {
    let root = root();
    for path in LAYERS
        .iter()
        .map(|layer| layer.source)
        .chain(["crates/riffdb-proto/src/public_message.rs"])
    {
        let lines = read(&root, path).lines().count();
        assert!(lines < 4_000, "{path} has {lines} lines");
    }
}
