[package]
name = "riffdb-contract-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
riffdb-contract-ir = { path = "../riffdb-contract-ir", version = "0.1.0" }
riffdb-contract-syntax = { path = "../riffdb-contract-syntax", version = "0.1.0" }
riffdb-types = { path = "../riffdb-types", version = "0.1.0" }

[dev-dependencies]
proptest = { version = "1.11.0", default-features = false, features = ["std"] }

[lints]
workspace = true
