from typing import Self

class NativeError(Exception): ...
class _BearerCredential:
    def __init__(self, token: str) -> None: ...
    @classmethod
    def from_protected_file(cls, path: str) -> Self: ...
    def has_same_presentation(self, other: _BearerCredential) -> bool: ...
class _CallMetadata:
    def __init__(
        self,
        credential: _BearerCredential | None = ...,
        database: str | None = ...,
        trace_parent: str | None = ...,
    ) -> None: ...
class _SyncClient:
    @classmethod
    def connect_uri(cls, endpoint: str, metadata: _CallMetadata) -> Self: ...
    @classmethod
    def connect_verified_tls(cls, endpoint: str, trust_root: str, server_name: str, pool_connections: int, streams_per_connection: int, metadata: _CallMetadata) -> Self: ...
    def execute_named_query(self, request: str) -> str: ...
    def execute_command(self, request: str) -> str: ...
    def close(self) -> None: ...
class _AsyncClient:
    async def execute_named_query(self, request: str) -> str: ...
    async def execute_command(self, request: str) -> str: ...
    async def consume_event_stream(self, request: str) -> str: ...
    async def consume_contextual_subscription(self, request: str) -> str: ...
    async def mutate_contextual_subscription(self, request: str) -> str: ...
    async def contextual_subscription_status(self, request: str) -> str: ...
    async def execute_contextual_reaction(self, request: str) -> str: ...
    async def mutate_event_consumer(self, request: str) -> str: ...
    async def seek_event_consumer(self, request: str) -> str: ...
    async def event_consumer_status(self, request: str) -> str: ...
    async def watch_named_query(self, request: str) -> str: ...
    async def close(self) -> None: ...
async def connect_async(endpoint: str, metadata: _CallMetadata) -> _AsyncClient: ...
async def connect_async_verified_tls(endpoint: str, trust_root: str, server_name: str, pool_connections: int, streams_per_connection: int, metadata: _CallMetadata) -> _AsyncClient: ...
def validate_bridge_value(source: str) -> None: ...
