[package]
name = "riffdb-api-grpc"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.0"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = []
client = ["tonic/channel"]

[dependencies]
base64 = { version = "=0.22.1", default-features = false, features = ["alloc"] }
riffdb-errors = { version = "0.1.0", path = "../riffdb-errors", default-features = false }
riffdb-proto = { version = "0.1.0", path = "../riffdb-proto", default-features = false }
tonic = { version = "=0.14.6", default-features = false, features = ["codegen"] }
tonic-prost = { version = "=0.14.6", default-features = false }

[build-dependencies]
prost = { version = "=0.14.4", default-features = false, features = ["std"] }
prost-types = { version = "=0.14.4", default-features = false, features = ["std"] }
riffdb-proto = { version = "0.1.0", path = "../riffdb-proto", default-features = false }
tonic-prost-build = { version = "=0.14.6", default-features = false, features = ["transport"] }

[lints]
workspace = true
