[package]
name = "riffdb-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
riffdb-contract-compiler = { path = "../riffdb-contract-compiler", version = "0.1.0" }
riffdb-contract-ir = { path = "../riffdb-contract-ir", version = "0.1.0", default-features = false }
riffdb-invariant = { path = "../riffdb-invariant", version = "0.1.0", default-features = false }
riffdb-runtime = { path = "../riffdb-runtime", version = "0.1.0", default-features = false }
riffdb-storage-api = { path = "../riffdb-storage-api", version = "0.1.0" }
riffdb-types = { path = "../riffdb-types", version = "0.1.0" }

[lints]
workspace = true
