//! Deterministic Python application-binding generation.

use std::collections::BTreeSet;
use std::fmt::{self, Write as _};

use riffdb_contract_ir::{ContractBundle, RecordTypeRef, ValueType, ValueTypeTag};
use riffdb_query_ir::NamedTypeSchema;

use crate::QueryModule;

/// Closed Python binding generation failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PythonGenerationError {
    /// Two source symbols normalize to the same Python identifier.
    NameCollision,
}

impl fmt::Display for PythonGenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("application symbols collide after Python name normalization")
    }
}

impl std::error::Error for PythonGenerationError {}

/// Generates one complete, identity-pinned Python application module.
pub fn generate_python_client(
    module: &QueryModule,
    contract: &ContractBundle,
) -> Result<String, PythonGenerationError> {
    validate_names(module, contract)?;
    let mut output = String::new();
    writeln!(
        output,
        "# @generated by riffdb-query-module; do not edit.\n\
         from __future__ import annotations\n\n\
         from collections.abc import Callable, Sequence\n\
         from dataclasses import dataclass, field\n\
         from decimal import Decimal\n\
         from enum import StrEnum\n\
         from typing import Annotated, Final, Literal, TypeAlias\n\
         from uuid import UUID\n\n\
         from riffdb_application import (\n\
             AsyncApplicationTransport, AttemptBudget, CommandBatchOptions,\n\
             CommandBatchProgress, CommandBatchResult, Money, QueryOptions, RiffDate,\n\
             SyncApplicationTransport, Timestamp, TypedCommandResult, TypedQueryResult,\n\
         )\n\
         from riffdb_application._binding import decode_variant, encode_record\n"
    )
    .expect("String writes cannot fail");
    writeln!(
        output,
        "CONTRACT_LINEAGE: Final[str] = {:?}\nCONTRACT_VERSION: Final[int] = {}\n\
         CONTRACT_BUNDLE_HASH: Final[str] = {:?}\nQUERY_MODULE_HASH: Final[str] = {:?}\n",
        module.contract_lineage().as_str(),
        module.contract_version().get(),
        hex(module.contract_hash().as_bytes()),
        hex(module.identity().as_bytes()),
    )
    .expect("String writes cannot fail");

    for enumeration in contract.schema().enums() {
        writeln!(output, "class {}(StrEnum):", pascal(enumeration.name()))
            .expect("String writes cannot fail");
        for variant in enumeration.variants() {
            writeln!(
                output,
                "    {} = {:?}",
                screaming_snake(variant.name()),
                variant.name()
            )
            .expect("String writes cannot fail");
        }
        output.push('\n');
    }

    for entity in contract.schema().entities() {
        emit_contract_record(
            &mut output,
            &pascal(entity.name()),
            entity
                .record()
                .fields()
                .iter()
                .map(|field| (field.name(), field.value_type())),
            contract,
        );
    }

    for query in module.queries() {
        let wire_name = query.name();
        let name = pascal(wire_name);
        let schemas = query.program().surface().schemas();
        for parameter in schemas.parameters() {
            emit_named_nested(
                &mut output,
                &format!("{name}Params{}", pascal(parameter.name())),
                parameter.value_type(),
                contract,
            );
        }
        writeln!(
            output,
            "{}_QUERY_PLAN_HASH: Final[str] = {:?}\n\n@dataclass(frozen=True, slots=True, kw_only=True)\nclass {name}Params:",
            screaming_snake(wire_name),
            hex(query.program().identity().hash().as_bytes())
        )
        .expect("String writes cannot fail");
        if schemas.parameters().is_empty() {
            output.push_str("    pass\n");
        }
        for parameter in schemas.parameters() {
            let nested = format!("{name}Params{}", pascal(parameter.name()));
            let defaulted = parameter.has_default() || is_cursor(parameter.value_type());
            let mut value_type = python_named_type(parameter.value_type(), &nested, contract);
            let default = if defaulted {
                if !value_type.ends_with(" | None") {
                    value_type.push_str(" | None");
                }
                " = None"
            } else {
                ""
            };
            writeln!(
                output,
                "    {}: {value_type}{default}",
                python_identifier(parameter.name())
            )
            .expect("String writes cannot fail");
        }
        output.push('\n');
        for branch in schemas.results() {
            let branch_name = format!("{name}{}", pascal(branch.name()));
            for result_field in branch.fields() {
                emit_named_nested(
                    &mut output,
                    &format!("{branch_name}{}", pascal(result_field.name())),
                    result_field.value_type(),
                    contract,
                );
            }
            writeln!(
                output,
                "@dataclass(frozen=True, slots=True, kw_only=True)\nclass {branch_name}:"
            )
            .expect("String writes cannot fail");
            for result_field in branch.fields() {
                let nested = format!("{branch_name}{}", pascal(result_field.name()));
                writeln!(
                    output,
                    "    {}: {}",
                    python_identifier(result_field.name()),
                    python_named_type(result_field.value_type(), &nested, contract)
                )
                .expect("String writes cannot fail");
            }
            writeln!(
                output,
                "    outcome: Literal[{:?}] = field(default={:?}, init=False)\n",
                branch.name(),
                branch.name()
            )
            .expect("String writes cannot fail");
        }
        write!(output, "{name}Result: TypeAlias = ").expect("String writes cannot fail");
        for (index, branch) in schemas.results().iter().enumerate() {
            if index != 0 {
                output.push_str(" | ");
            }
            write!(output, "{name}{}", pascal(branch.name())).expect("String writes cannot fail");
        }
        output.push_str("\n\n");
    }

    let mut commands = contract.commands().iter().collect::<Vec<_>>();
    commands.sort_by(|left, right| left.name().cmp(right.name()));
    for command in &commands {
        let wire_name = command.name();
        let name = pascal(wire_name);
        emit_contract_record(
            &mut output,
            &format!("{name}Input"),
            command
                .input()
                .record()
                .fields()
                .iter()
                .map(|field| (field.name(), field.value_type())),
            contract,
        );
        writeln!(
            output,
            "{}_PLAN_HASH: Final[str] = {:?}",
            screaming_snake(wire_name),
            hex(command.plan_hash().as_bytes())
        )
        .expect("String writes cannot fail");
        for outcome in command.outcomes() {
            let outcome_name = format!("{name}{}", pascal(outcome.name()));
            writeln!(
                output,
                "@dataclass(frozen=True, slots=True, kw_only=True)\nclass {outcome_name}:"
            )
            .expect("String writes cannot fail");
            for payload_field in outcome.payload().fields() {
                writeln!(
                    output,
                    "    {}: {}",
                    python_identifier(payload_field.name()),
                    python_contract_type(payload_field.value_type(), contract)
                )
                .expect("String writes cannot fail");
            }
            writeln!(
                output,
                "    outcome: Literal[{:?}] = field(default={:?}, init=False)\n",
                outcome.name(),
                outcome.name()
            )
            .expect("String writes cannot fail");
        }
        write!(output, "{name}Outcome: TypeAlias = ").expect("String writes cannot fail");
        for (index, outcome) in command.outcomes().iter().enumerate() {
            if index != 0 {
                output.push_str(" | ");
            }
            write!(output, "{name}{}", pascal(outcome.name())).expect("String writes cannot fail");
        }
        output.push_str("\n\n");
    }

    emit_client(&mut output, module, &commands, false);
    emit_client(&mut output, module, &commands, true);
    while output.ends_with("\n\n") {
        output.pop();
    }
    Ok(output)
}

fn emit_client(
    output: &mut String,
    module: &QueryModule,
    commands: &[&riffdb_contract_ir::CommandPlan],
    asynchronous: bool,
) {
    let prefix = if asynchronous { "Async" } else { "" };
    let transport = if asynchronous {
        "AsyncApplicationTransport"
    } else {
        "SyncApplicationTransport"
    };
    let await_token = if asynchronous { "await " } else { "" };
    writeln!(
        output,
        "class {prefix}{}Client:\n    def __init__(self, transport: {transport}, command_attempts: AttemptBudget) -> None:\n        self._transport = transport\n        self._command_attempts = command_attempts\n",
        pascal(module.contract_lineage().as_str())
    )
    .expect("String writes cannot fail");
    for query in module.queries() {
        let wire_name = query.name();
        let name = pascal(wire_name);
        let method = python_identifier(&snake(wire_name));
        let async_token = if asynchronous { "async " } else { "" };
        writeln!(
            output,
            "    {async_token}def {method}(self, parameters: {name}Params, options: QueryOptions = QueryOptions()) -> TypedQueryResult[{name}Result]:\n        raw = {await_token}self._transport._execute_named_query(\n            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,\n            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,\n            query_name={wire_name:?}, plan_hash={constant}_QUERY_PLAN_HASH,\n            parameters=encode_record(parameters), options=options,\n        )\n        outcomes = {{",
            constant = screaming_snake(wire_name)
        )
        .expect("String writes cannot fail");
        for branch in query.program().surface().schemas().results() {
            writeln!(
                output,
                "            {:?}: {name}{},",
                branch.name(),
                pascal(branch.name())
            )
            .expect("String writes cannot fail");
        }
        output.push_str(
            "        }\n        return raw._map_value(lambda value: decode_variant(outcomes, value))\n\n",
        );
    }
    for command in commands {
        let wire_name = command.name();
        let name = pascal(wire_name);
        let method = python_identifier(&snake(wire_name));
        let async_token = if asynchronous { "async " } else { "" };
        writeln!(
            output,
            "    {async_token}def {method}(self, input: {name}Input) -> TypedCommandResult[{name}Outcome]:\n        raw = {await_token}self._transport._execute_command(\n            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,\n            command_name={wire_name:?}, plan_hash={constant}_PLAN_HASH,\n            input=encode_record(input), attempts=self._command_attempts,\n        )\n        outcomes = {{",
            constant = screaming_snake(wire_name)
        )
        .expect("String writes cannot fail");
        for outcome in command.outcomes() {
            writeln!(
                output,
                "            {:?}: {name}{},",
                outcome.name(),
                pascal(outcome.name())
            )
            .expect("String writes cannot fail");
        }
        output.push_str(
            "        }\n        return raw._map_outcome(lambda value: decode_variant(outcomes, value))\n\n",
        );
        let batch_await = if asynchronous { "await " } else { "" };
        writeln!(
            output,
            "    {async_token}def {method}_batch(\n        self, inputs: Sequence[{name}Input], options: CommandBatchOptions,\n        progress: Callable[[CommandBatchProgress], None] | None = None,\n    ) -> CommandBatchResult[{name}Outcome]:\n        return {batch_await}self._transport._command_batch(inputs, options, self.{method}, progress)\n"
        )
        .expect("String writes cannot fail");
    }
}

fn emit_contract_record<'a>(
    output: &mut String,
    name: &str,
    fields: impl Iterator<Item = (&'a str, &'a ValueType)>,
    contract: &ContractBundle,
) {
    let fields = fields.collect::<Vec<_>>();
    writeln!(
        output,
        "@dataclass(frozen=True, slots=True, kw_only=True)\nclass {name}:"
    )
    .expect("String writes cannot fail");
    if fields.is_empty() {
        output.push_str("    pass\n");
    }
    for (field, value_type) in fields {
        writeln!(
            output,
            "    {}: {}",
            python_identifier(field),
            python_contract_type(value_type, contract)
        )
        .expect("String writes cannot fail");
    }
    output.push('\n');
}

fn emit_named_nested(
    output: &mut String,
    name: &str,
    value_type: &NamedTypeSchema,
    contract: &ContractBundle,
) {
    match value_type {
        NamedTypeSchema::Optional(inner)
        | NamedTypeSchema::Set(inner)
        | NamedTypeSchema::List { element: inner, .. } => {
            emit_named_nested(output, name, inner, contract);
        }
        NamedTypeSchema::Record(fields) => {
            for field in fields {
                emit_named_nested(
                    output,
                    &format!("{name}{}", pascal(field.name())),
                    field.value_type(),
                    contract,
                );
            }
            writeln!(
                output,
                "@dataclass(frozen=True, slots=True, kw_only=True)\nclass {name}:"
            )
            .expect("String writes cannot fail");
            if fields.is_empty() {
                output.push_str("    pass\n");
            }
            for field in fields {
                writeln!(
                    output,
                    "    {}: {}",
                    python_identifier(field.name()),
                    python_named_type(
                        field.value_type(),
                        &format!("{name}{}", pascal(field.name())),
                        contract
                    )
                )
                .expect("String writes cannot fail");
            }
            output.push('\n');
        }
        NamedTypeSchema::Scalar(_) | NamedTypeSchema::Cursor | NamedTypeSchema::Limit => {}
    }
}

fn python_named_type(
    value_type: &NamedTypeSchema,
    nested_name: &str,
    contract: &ContractBundle,
) -> String {
    match value_type {
        NamedTypeSchema::Scalar(name) => match name.as_str() {
            "bool" => "bool".to_owned(),
            "i64" => "Annotated[int, \"i64\"]".to_owned(),
            "u64" => "Annotated[int, \"u64\"]".to_owned(),
            "uuid" => "UUID".to_owned(),
            "timestamp" => "Timestamp".to_owned(),
            "date" => "RiffDate".to_owned(),
            value if value.starts_with("bytes<") => "bytes".to_owned(),
            value if value.starts_with("decimal<") => "Decimal".to_owned(),
            value
                if contract
                    .schema()
                    .enums()
                    .iter()
                    .any(|enumeration| enumeration.name() == value) =>
            {
                pascal(value)
            }
            _ => "str".to_owned(),
        },
        NamedTypeSchema::Optional(inner) => {
            format!("{} | None", python_named_type(inner, nested_name, contract))
        }
        NamedTypeSchema::Set(inner) | NamedTypeSchema::List { element: inner, .. } => {
            format!(
                "tuple[{}, ...]",
                python_named_type(inner, nested_name, contract)
            )
        }
        NamedTypeSchema::Record(_) => nested_name.to_owned(),
        NamedTypeSchema::Cursor => "str".to_owned(),
        NamedTypeSchema::Limit => "Annotated[int, \"u64\"]".to_owned(),
    }
}

fn python_contract_type(value_type: &ValueType, contract: &ContractBundle) -> String {
    if let Some(inner) = value_type.optional_inner() {
        return format!("{} | None", python_contract_type(inner, contract));
    }
    if let Some((inner, _)) = value_type.list_parts() {
        return format!("tuple[{}, ...]", python_contract_type(inner, contract));
    }
    match value_type.tag() {
        ValueTypeTag::Bool => "bool".to_owned(),
        ValueTypeTag::I64 => "Annotated[int, \"i64\"]".to_owned(),
        ValueTypeTag::U64 => "Annotated[int, \"u64\"]".to_owned(),
        ValueTypeTag::Bytes => "bytes".to_owned(),
        ValueTypeTag::Decimal => "Decimal".to_owned(),
        ValueTypeTag::Money => "Money".to_owned(),
        ValueTypeTag::Timestamp => "Timestamp".to_owned(),
        ValueTypeTag::Date => "RiffDate".to_owned(),
        ValueTypeTag::Uuid => "UUID".to_owned(),
        ValueTypeTag::Enum => value_type
            .enum_type_id()
            .and_then(|id| contract.schema().enumeration(id))
            .map_or_else(|| "str".to_owned(), |value| pascal(value.name())),
        ValueTypeTag::Record => match value_type.record_ref() {
            Some(RecordTypeRef::Entity(id)) => contract
                .schema()
                .entity(*id)
                .map_or_else(|| "str".to_owned(), |entity| pascal(entity.name())),
            _ => "str".to_owned(),
        },
        ValueTypeTag::String => "str".to_owned(),
        ValueTypeTag::Optional | ValueTypeTag::List => unreachable!("handled above"),
    }
}

fn validate_names(
    module: &QueryModule,
    contract: &ContractBundle,
) -> Result<(), PythonGenerationError> {
    let mut top_level = PYTHON_RESERVED_TOP_LEVEL
        .iter()
        .map(|name| (*name).to_owned())
        .collect::<BTreeSet<_>>();
    let mut methods = BTreeSet::new();

    for enumeration in contract.schema().enums() {
        insert_name(&mut top_level, pascal(enumeration.name()))?;
        validate_normalized_names(
            enumeration
                .variants()
                .iter()
                .map(|variant| screaming_snake(variant.name())),
            false,
        )?;
    }
    for entity in contract.schema().entities() {
        insert_name(&mut top_level, pascal(entity.name()))?;
        validate_normalized_names(
            entity
                .record()
                .fields()
                .iter()
                .map(|field| python_identifier(field.name())),
            false,
        )?;
    }
    for query in module.queries() {
        let name = pascal(query.name());
        insert_name(&mut top_level, format!("{name}Params"))?;
        insert_name(&mut top_level, format!("{name}Result"))?;
        insert_name(
            &mut top_level,
            format!("{}_QUERY_PLAN_HASH", screaming_snake(query.name())),
        )?;
        insert_name(&mut methods, python_identifier(&snake(query.name())))?;

        let schemas = query.program().surface().schemas();
        validate_normalized_names(
            schemas
                .parameters()
                .iter()
                .map(|field| python_identifier(field.name())),
            false,
        )?;
        for parameter in schemas.parameters() {
            register_nested_names(
                &mut top_level,
                &format!("{name}Params{}", pascal(parameter.name())),
                parameter.value_type(),
            )?;
        }
        for branch in schemas.results() {
            let branch_name = format!("{name}{}", pascal(branch.name()));
            insert_name(&mut top_level, branch_name.clone())?;
            validate_normalized_names(
                branch
                    .fields()
                    .iter()
                    .map(|field| python_identifier(field.name())),
                true,
            )?;
            for field in branch.fields() {
                register_nested_names(
                    &mut top_level,
                    &format!("{branch_name}{}", pascal(field.name())),
                    field.value_type(),
                )?;
            }
        }
    }
    for command in contract.commands() {
        let name = pascal(command.name());
        insert_name(&mut top_level, format!("{name}Input"))?;
        insert_name(&mut top_level, format!("{name}Outcome"))?;
        insert_name(
            &mut top_level,
            format!("{}_PLAN_HASH", screaming_snake(command.name())),
        )?;
        let method = python_identifier(&snake(command.name()));
        insert_name(&mut methods, method.clone())?;
        insert_name(&mut methods, format!("{method}_batch"))?;
        validate_normalized_names(
            command
                .input()
                .record()
                .fields()
                .iter()
                .map(|field| python_identifier(field.name())),
            false,
        )?;
        for outcome in command.outcomes() {
            insert_name(&mut top_level, format!("{name}{}", pascal(outcome.name())))?;
            validate_normalized_names(
                outcome
                    .payload()
                    .fields()
                    .iter()
                    .map(|field| python_identifier(field.name())),
                true,
            )?;
        }
    }
    insert_name(
        &mut top_level,
        format!("{}Client", pascal(module.contract_lineage().as_str())),
    )?;
    insert_name(
        &mut top_level,
        format!("Async{}Client", pascal(module.contract_lineage().as_str())),
    )?;
    Ok(())
}

fn register_nested_names(
    top_level: &mut BTreeSet<String>,
    name: &str,
    value_type: &NamedTypeSchema,
) -> Result<(), PythonGenerationError> {
    match value_type {
        NamedTypeSchema::Optional(inner)
        | NamedTypeSchema::Set(inner)
        | NamedTypeSchema::List { element: inner, .. } => {
            register_nested_names(top_level, name, inner)
        }
        NamedTypeSchema::Record(fields) => {
            insert_name(top_level, name.to_owned())?;
            validate_normalized_names(
                fields.iter().map(|field| python_identifier(field.name())),
                false,
            )?;
            for field in fields {
                register_nested_names(
                    top_level,
                    &format!("{name}{}", pascal(field.name())),
                    field.value_type(),
                )?;
            }
            Ok(())
        }
        NamedTypeSchema::Scalar(_) | NamedTypeSchema::Cursor | NamedTypeSchema::Limit => Ok(()),
    }
}

fn validate_normalized_names(
    names: impl IntoIterator<Item = String>,
    reserve_outcome: bool,
) -> Result<(), PythonGenerationError> {
    let mut normalized = BTreeSet::new();
    if reserve_outcome {
        normalized.insert("outcome".to_owned());
    }
    for name in names {
        insert_name(&mut normalized, name)?;
    }
    Ok(())
}

fn insert_name(names: &mut BTreeSet<String>, name: String) -> Result<(), PythonGenerationError> {
    if name.is_empty() || !names.insert(name) {
        return Err(PythonGenerationError::NameCollision);
    }
    Ok(())
}

const PYTHON_RESERVED_TOP_LEVEL: &[&str] = &[
    "Annotated",
    "AsyncApplicationTransport",
    "AttemptBudget",
    "CONTRACT_BUNDLE_HASH",
    "CONTRACT_LINEAGE",
    "CONTRACT_VERSION",
    "Callable",
    "CommandBatchOptions",
    "CommandBatchProgress",
    "CommandBatchResult",
    "Decimal",
    "Final",
    "Literal",
    "Money",
    "QUERY_MODULE_HASH",
    "QueryOptions",
    "RiffDate",
    "Sequence",
    "StrEnum",
    "SyncApplicationTransport",
    "Timestamp",
    "TypeAlias",
    "TypedCommandResult",
    "TypedQueryResult",
    "UUID",
    "dataclass",
    "decode_variant",
    "encode_record",
    "field",
];

fn is_cursor(value_type: &NamedTypeSchema) -> bool {
    matches!(value_type, NamedTypeSchema::Cursor)
        || matches!(value_type, NamedTypeSchema::Optional(inner) if is_cursor(inner))
}

fn python_identifier(name: &str) -> String {
    let value = snake(name);
    if PYTHON_KEYWORDS.contains(&value.as_str()) {
        format!("{value}_")
    } else {
        value
    }
}

const PYTHON_KEYWORDS: &[&str] = &[
    "and", "as", "assert", "async", "await", "break", "case", "class", "continue", "def", "del",
    "elif", "else", "except", "false", "finally", "for", "from", "global", "if", "import", "in",
    "is", "lambda", "match", "none", "nonlocal", "not", "or", "pass", "raise", "return", "true",
    "try", "while", "with", "yield",
];

fn snake(name: &str) -> String {
    separated(name, '_', false)
}

fn screaming_snake(name: &str) -> String {
    separated(name, '_', true)
}

fn pascal(name: &str) -> String {
    name.split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .flat_map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|character| character.to_ascii_uppercase())
                .into_iter()
                .chain(chars)
        })
        .collect()
}

fn separated(name: &str, separator: char, uppercase: bool) -> String {
    let mut output = String::new();
    let mut previous_lower = false;
    for character in name.chars() {
        if !character.is_ascii_alphanumeric() {
            if !output.ends_with(separator) && !output.is_empty() {
                output.push(separator);
            }
            previous_lower = false;
        } else {
            if character.is_ascii_uppercase() && previous_lower {
                output.push(separator);
            }
            output.push(if uppercase {
                character.to_ascii_uppercase()
            } else {
                character.to_ascii_lowercase()
            });
            previous_lower = character.is_ascii_lowercase() || character.is_ascii_digit();
        }
    }
    output
}

fn hex(bytes: &[u8]) -> String {
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(output, "{byte:02x}").expect("String writes cannot fail");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::{PythonGenerationError, python_identifier, validate_normalized_names};

    #[test]
    fn keywords_gain_one_suffix_and_collisions_are_rejected() {
        assert_eq!(python_identifier("class"), "class_");
        assert_eq!(python_identifier("ordinaryName"), "ordinary_name");
        assert_eq!(
            validate_normalized_names(
                [python_identifier("class"), python_identifier("class_")],
                false,
            ),
            Err(PythonGenerationError::NameCollision)
        );
        assert_eq!(
            validate_normalized_names([python_identifier("outcome")], true),
            Err(PythonGenerationError::NameCollision)
        );
    }
}
