# @generated by riffdb-query-module; do not edit.
from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from decimal import Decimal
from enum import StrEnum
from typing import Annotated, Final, Literal, TypeAlias
from uuid import UUID

from riffdb_application import (
AsyncApplicationTransport, AttemptBudget, CommandBatchOptions,
CommandBatchProgress, CommandBatchResult, Money, QueryOptions, RiffDate,
SyncApplicationTransport, Timestamp, TypedCommandResult, TypedQueryResult,
)
from riffdb_application._binding import decode_variant, encode_record

CONTRACT_LINEAGE: Final[str] = "TicketDesk"
CONTRACT_VERSION: Final[int] = 1
CONTRACT_BUNDLE_HASH: Final[str] = "cd221ebb44c57105da5bdb2682b473e4ce4cde4d7cac540e49097450df6ec7de"
QUERY_MODULE_HASH: Final[str] = "c1effc1f6684b2786f0b436bc691d6d9e82181d9e656902c6cbd1a553270f642"

class TicketStatus(StrEnum):
    OPEN = "Open"
    CLOSED = "Closed"
    IN_PROGRESS = "InProgress"

@dataclass(frozen=True, slots=True, kw_only=True)
class Label:
    name: str
    label_id: UUID
    created_at: Timestamp
    organization_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class Ticket:
    title: str
    status: TicketStatus
    ticket_id: UUID
    created_at: Timestamp
    project_id: UUID
    updated_at: Timestamp
    assignee_id: UUID
    reporter_id: UUID
    organization_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class AppUser:
    email: str
    user_id: UUID
    created_at: Timestamp
    display_name: str
    organization_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class Comment:
    body: str
    author_id: UUID
    ticket_id: UUID
    comment_id: UUID
    created_at: Timestamp
    organization_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class Project:
    name: str
    created_at: Timestamp
    project_id: UUID
    organization_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketLabel:
    label_id: UUID
    ticket_id: UUID
    created_at: Timestamp
    organization_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class Organization:
    name: str
    created_at: Timestamp
    organization_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectMember:
    role: str
    user_id: UUID
    created_at: Timestamp
    project_id: UUID
    organization_id: UUID

BOARD_PAGE200_QUERY_PLAN_HASH: Final[str] = "d0a4294c1ce4e0fe8883f4a382d445a4addf346d1ee6a39989f18521788b355a"

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage200Params:
    organization_id: UUID
    project_id: UUID
    status: TicketStatus

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage200FoundTickets:
    ticket_id: UUID
    project_id: UUID
    title: str
    status: TicketStatus
    reporter_id: UUID
    assignee_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage200Found:
    tickets: tuple[BoardPage200FoundTickets, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

BoardPage200Result: TypeAlias = BoardPage200Found

BOARD_PAGE450_QUERY_PLAN_HASH: Final[str] = "1047c13c0665d0c7e39e332dc766b64e690e5dd577e9864ba59dd8291ddf04d4"

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage450Params:
    organization_id: UUID
    project_id: UUID
    status: TicketStatus

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage450FoundTickets:
    ticket_id: UUID
    project_id: UUID
    title: str
    status: TicketStatus
    reporter_id: UUID
    assignee_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage450Found:
    tickets: tuple[BoardPage450FoundTickets, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

BoardPage450Result: TypeAlias = BoardPage450Found

BOARD_PAGE50_QUERY_PLAN_HASH: Final[str] = "35c9815474d34fbf61e5fa4d81375e9a89f1fb62ea2cccf70bd18db0aa83280e"

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage50Params:
    organization_id: UUID
    project_id: UUID
    status: TicketStatus

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage50FoundTickets:
    ticket_id: UUID
    project_id: UUID
    title: str
    status: TicketStatus
    reporter_id: UUID
    assignee_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class BoardPage50Found:
    tickets: tuple[BoardPage50FoundTickets, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

BoardPage50Result: TypeAlias = BoardPage50Found

GET_TICKET_QUERY_PLAN_HASH: Final[str] = "a3c62d90ae6fb48303631110c500933f3f06c20e141fdd1f681a484a7450ab0d"

@dataclass(frozen=True, slots=True, kw_only=True)
class GetTicketParams:
    organization_id: UUID
    ticket_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class GetTicketFoundTicket:
    ticket_id: UUID
    project_id: UUID
    title: str
    status: TicketStatus
    reporter_id: UUID
    assignee_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class GetTicketFound:
    ticket: GetTicketFoundTicket
    outcome: Literal["Found"] = field(default="Found", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class GetTicketNotFound:
    outcome: Literal["NotFound"] = field(default="NotFound", init=False)

GetTicketResult: TypeAlias = GetTicketFound | GetTicketNotFound

GET_USER_QUERY_PLAN_HASH: Final[str] = "13e3d239243777fe536c33a1f309fe8a17946de357a3745a1747d42b2f958930"

@dataclass(frozen=True, slots=True, kw_only=True)
class GetUserParams:
    organization_id: UUID
    user_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class GetUserFoundUser:
    user_id: UUID
    email: str
    display_name: str

@dataclass(frozen=True, slots=True, kw_only=True)
class GetUserFound:
    user: GetUserFoundUser
    outcome: Literal["Found"] = field(default="Found", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class GetUserNotFound:
    outcome: Literal["NotFound"] = field(default="NotFound", init=False)

GetUserResult: TypeAlias = GetUserFound | GetUserNotFound

LIST_COMMENTS_QUERY_PLAN_HASH: Final[str] = "e84f36413f039176575f94ca592aed2a81b914d39aa0a89d8e5228c2c20bd6d3"

@dataclass(frozen=True, slots=True, kw_only=True)
class ListCommentsParams:
    organization_id: UUID
    ticket_id: UUID
    after: str | None = None
    limit: Annotated[int, "u64"] | None = None

@dataclass(frozen=True, slots=True, kw_only=True)
class ListCommentsFoundComments:
    comment_id: UUID
    body: str
    author_id: UUID
    created_at: Timestamp

@dataclass(frozen=True, slots=True, kw_only=True)
class ListCommentsFound:
    comments: tuple[ListCommentsFoundComments, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

ListCommentsResult: TypeAlias = ListCommentsFound

LIST_TICKETS_QUERY_PLAN_HASH: Final[str] = "995f86da488685d9b7c32d13e43893fe278793246a2b7dd33bb9c019964d335b"

@dataclass(frozen=True, slots=True, kw_only=True)
class ListTicketsParams:
    organization_id: UUID
    project_id: UUID
    statuses: tuple[TicketStatus, ...]
    after: str | None = None
    limit: Annotated[int, "u64"] | None = None

@dataclass(frozen=True, slots=True, kw_only=True)
class ListTicketsFoundTickets:
    ticket_id: UUID
    project_id: UUID
    title: str
    status: TicketStatus
    updated_at: Timestamp
    reporter_id: UUID
    assignee_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class ListTicketsFound:
    tickets: tuple[ListTicketsFoundTickets, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

ListTicketsResult: TypeAlias = ListTicketsFound

LIST_TICKETS_BY_ASSIGNEE_QUERY_PLAN_HASH: Final[str] = "aea9cbc9f3fb7de36b6f3504ea536921ae008204b7ef7472437f701f0c5b300c"

@dataclass(frozen=True, slots=True, kw_only=True)
class ListTicketsByAssigneeParams:
    organization_id: UUID
    assignee_id: UUID
    statuses: tuple[TicketStatus, ...]
    after: str | None = None
    limit: Annotated[int, "u64"] | None = None

@dataclass(frozen=True, slots=True, kw_only=True)
class ListTicketsByAssigneeFoundTickets:
    ticket_id: UUID
    project_id: UUID
    title: str
    status: TicketStatus
    updated_at: Timestamp
    reporter_id: UUID
    assignee_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class ListTicketsByAssigneeFound:
    tickets: tuple[ListTicketsByAssigneeFoundTickets, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

ListTicketsByAssigneeResult: TypeAlias = ListTicketsByAssigneeFound

PROJECT_MEMBERS_QUERY_PLAN_HASH: Final[str] = "273e025bc51fcf488794f28c45746c0ff180a6955d414873feac581a22708f7b"

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectMembersParams:
    organization_id: UUID
    project_id: UUID
    after: str | None = None

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectMembersFoundMembers:
    user_id: UUID
    role: str

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectMembersFound:
    members: tuple[ProjectMembersFoundMembers, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

ProjectMembersResult: TypeAlias = ProjectMembersFound

PROJECT_SUMMARY_QUERY_PLAN_HASH: Final[str] = "281b68867d9a37f1f3367fd4b63b14dd8533b60c385238cac774a3bcd5936d7e"

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectSummaryParams:
    organization_id: UUID
    project_id: UUID
    status: TicketStatus

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectSummaryFoundProject:
    project_id: UUID
    name: str

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectSummaryFoundRecentTickets:
    ticket_id: UUID
    title: str
    status: TicketStatus
    updated_at: Timestamp

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectSummaryFound:
    project: ProjectSummaryFoundProject
    recent_tickets: tuple[ProjectSummaryFoundRecentTickets, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class ProjectSummaryNotFound:
    outcome: Literal["NotFound"] = field(default="NotFound", init=False)

ProjectSummaryResult: TypeAlias = ProjectSummaryFound | ProjectSummaryNotFound

TICKET_PAGE_QUERY_PLAN_HASH: Final[str] = "ac390a2d26f0d6a9e2f0587fb2fed428910c6e6175fe47de9e40c47a29a979d5"

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageParams:
    organization_id: UUID
    ticket_id: UUID

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFoundTicket:
    ticket_id: UUID
    project_id: UUID
    title: str
    status: TicketStatus
    created_at: Timestamp
    updated_at: Timestamp

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFoundProject:
    project_id: UUID
    name: str

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFoundOrganization:
    organization_id: UUID
    name: str

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFoundReporter:
    user_id: UUID
    display_name: str

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFoundAssignee:
    user_id: UUID
    display_name: str

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFoundComments:
    comment_id: UUID
    body: str
    author_id: UUID
    created_at: Timestamp

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFoundLabels:
    label_id: UUID
    name: str

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageFound:
    ticket: TicketPageFoundTicket
    project: TicketPageFoundProject
    organization: TicketPageFoundOrganization
    reporter: TicketPageFoundReporter
    assignee: TicketPageFoundAssignee | None
    comments: tuple[TicketPageFoundComments, ...]
    labels: tuple[TicketPageFoundLabels, ...]
    outcome: Literal["Found"] = field(default="Found", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageNotFound:
    outcome: Literal["NotFound"] = field(default="NotFound", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class TicketPageIntegrityFailure:
    outcome: Literal["IntegrityFailure"] = field(default="IntegrityFailure", init=False)

TicketPageResult: TypeAlias = TicketPageFound | TicketPageNotFound | TicketPageIntegrityFailure

@dataclass(frozen=True, slots=True, kw_only=True)
class AddProjectMemberInput:
    role: str
    user_id: UUID
    project_id: UUID
    idempotency_key: str
    organization_id: UUID

ADD_PROJECT_MEMBER_PLAN_HASH: Final[str] = "65a0a5eedbc1dd1704da23be83c989c564e106f555511ac9c8fd2e986241b644"
@dataclass(frozen=True, slots=True, kw_only=True)
class AddProjectMemberCreated:
    member: ProjectMember
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class AddProjectMemberUserMissing:
    user_id: UUID
    outcome: Literal["UserMissing"] = field(default="UserMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class AddProjectMemberMemberExists:
    user_id: UUID
    project_id: UUID
    outcome: Literal["MemberExists"] = field(default="MemberExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class AddProjectMemberProjectMissing:
    project_id: UUID
    outcome: Literal["ProjectMissing"] = field(default="ProjectMissing", init=False)

AddProjectMemberOutcome: TypeAlias = AddProjectMemberCreated | AddProjectMemberUserMissing | AddProjectMemberMemberExists | AddProjectMemberProjectMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class AttachLabelInput:
    label_id: UUID
    ticket_id: UUID
    idempotency_key: str
    organization_id: UUID

ATTACH_LABEL_PLAN_HASH: Final[str] = "c17660b5bd5160390772aac001925acc2017273fe03bf39723094ff769b73a43"
@dataclass(frozen=True, slots=True, kw_only=True)
class AttachLabelCreated:
    link: TicketLabel
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class AttachLabelLinkExists:
    label_id: UUID
    ticket_id: UUID
    outcome: Literal["LinkExists"] = field(default="LinkExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class AttachLabelLabelMissing:
    label_id: UUID
    outcome: Literal["LabelMissing"] = field(default="LabelMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class AttachLabelTicketMissing:
    ticket_id: UUID
    outcome: Literal["TicketMissing"] = field(default="TicketMissing", init=False)

AttachLabelOutcome: TypeAlias = AttachLabelCreated | AttachLabelLinkExists | AttachLabelLabelMissing | AttachLabelTicketMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class CloseTicketWithCommentInput:
    body: str
    author_id: UUID
    ticket_id: UUID
    comment_id: UUID
    idempotency_key: str
    organization_id: UUID

CLOSE_TICKET_WITH_COMMENT_PLAN_HASH: Final[str] = "f126142eed87d07f3b8dd3b82e09ee48c430c23583d50196c2ad17ed59bf91d7"
@dataclass(frozen=True, slots=True, kw_only=True)
class CloseTicketWithCommentClosed:
    ticket: Ticket
    comment: Comment
    outcome: Literal["Closed"] = field(default="Closed", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CloseTicketWithCommentTicketGone:
    ticket_id: UUID
    outcome: Literal["TicketGone"] = field(default="TicketGone", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CloseTicketWithCommentAuthorMissing:
    user_id: UUID
    outcome: Literal["AuthorMissing"] = field(default="AuthorMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CloseTicketWithCommentCommentExists:
    comment_id: UUID
    outcome: Literal["CommentExists"] = field(default="CommentExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CloseTicketWithCommentTicketMissing:
    ticket_id: UUID
    outcome: Literal["TicketMissing"] = field(default="TicketMissing", init=False)

CloseTicketWithCommentOutcome: TypeAlias = CloseTicketWithCommentClosed | CloseTicketWithCommentTicketGone | CloseTicketWithCommentAuthorMissing | CloseTicketWithCommentCommentExists | CloseTicketWithCommentTicketMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateCommentInput:
    body: str
    author_id: UUID
    ticket_id: UUID
    comment_id: UUID
    idempotency_key: str
    organization_id: UUID

CREATE_COMMENT_PLAN_HASH: Final[str] = "5456fbeb4b1781f6707104a3182c809fd3af7a0dbdfaf5d6498d1eee0a5a5529"
@dataclass(frozen=True, slots=True, kw_only=True)
class CreateCommentCreated:
    comment: Comment
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateCommentAuthorMissing:
    user_id: UUID
    outcome: Literal["AuthorMissing"] = field(default="AuthorMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateCommentCommentExists:
    comment_id: UUID
    outcome: Literal["CommentExists"] = field(default="CommentExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateCommentTicketMissing:
    ticket_id: UUID
    outcome: Literal["TicketMissing"] = field(default="TicketMissing", init=False)

CreateCommentOutcome: TypeAlias = CreateCommentCreated | CreateCommentAuthorMissing | CreateCommentCommentExists | CreateCommentTicketMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateLabelInput:
    name: str
    label_id: UUID
    idempotency_key: str
    organization_id: UUID

CREATE_LABEL_PLAN_HASH: Final[str] = "155f02767ffaf89274561414d96c1332faed06254e27e5f75e12ee2322849e75"
@dataclass(frozen=True, slots=True, kw_only=True)
class CreateLabelCreated:
    label: Label
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateLabelLabelExists:
    label_id: UUID
    outcome: Literal["LabelExists"] = field(default="LabelExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateLabelOrganizationMissing:
    organization_id: UUID
    outcome: Literal["OrganizationMissing"] = field(default="OrganizationMissing", init=False)

CreateLabelOutcome: TypeAlias = CreateLabelCreated | CreateLabelLabelExists | CreateLabelOrganizationMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateOrganizationInput:
    name: str
    idempotency_key: str
    organization_id: UUID

CREATE_ORGANIZATION_PLAN_HASH: Final[str] = "1dc12f73b47fac29c8159c7b0217357e1215edfc198282bd3bc5a3f6ee531205"
@dataclass(frozen=True, slots=True, kw_only=True)
class CreateOrganizationCreated:
    organization: Organization
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateOrganizationOrganizationExists:
    organization_id: UUID
    outcome: Literal["OrganizationExists"] = field(default="OrganizationExists", init=False)

CreateOrganizationOutcome: TypeAlias = CreateOrganizationCreated | CreateOrganizationOrganizationExists

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateProjectInput:
    name: str
    project_id: UUID
    idempotency_key: str
    organization_id: UUID

CREATE_PROJECT_PLAN_HASH: Final[str] = "ad382ce1fb915985b0b0170fadc7b2e7313aa5446554be13773394a7f25a5124"
@dataclass(frozen=True, slots=True, kw_only=True)
class CreateProjectCreated:
    project: Project
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateProjectProjectExists:
    project_id: UUID
    outcome: Literal["ProjectExists"] = field(default="ProjectExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateProjectOrganizationMissing:
    organization_id: UUID
    outcome: Literal["OrganizationMissing"] = field(default="OrganizationMissing", init=False)

CreateProjectOutcome: TypeAlias = CreateProjectCreated | CreateProjectProjectExists | CreateProjectOrganizationMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateTicketInput:
    title: str
    status: TicketStatus
    ticket_id: UUID
    project_id: UUID
    assignee_id: UUID
    reporter_id: UUID
    idempotency_key: str
    organization_id: UUID

CREATE_TICKET_PLAN_HASH: Final[str] = "cfaebe79ac6ac9288a0b5e7982d659eacb2aad088eb87c4496ae3d5cdbe9bfc6"
@dataclass(frozen=True, slots=True, kw_only=True)
class CreateTicketCreated:
    ticket: Ticket
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateTicketTicketExists:
    ticket_id: UUID
    outcome: Literal["TicketExists"] = field(default="TicketExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateTicketProjectMissing:
    project_id: UUID
    outcome: Literal["ProjectMissing"] = field(default="ProjectMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateTicketAssigneeMissing:
    user_id: UUID
    outcome: Literal["AssigneeMissing"] = field(default="AssigneeMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateTicketReporterMissing:
    user_id: UUID
    outcome: Literal["ReporterMissing"] = field(default="ReporterMissing", init=False)

CreateTicketOutcome: TypeAlias = CreateTicketCreated | CreateTicketTicketExists | CreateTicketProjectMissing | CreateTicketAssigneeMissing | CreateTicketReporterMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateUserInput:
    email: str
    user_id: UUID
    display_name: str
    idempotency_key: str
    organization_id: UUID

CREATE_USER_PLAN_HASH: Final[str] = "ec5c88b02cbf31705aef2d5224c363a883346623979dd0fb4e6403ec29f351fd"
@dataclass(frozen=True, slots=True, kw_only=True)
class CreateUserCreated:
    user: AppUser
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateUserUserExists:
    user_id: UUID
    outcome: Literal["UserExists"] = field(default="UserExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class CreateUserOrganizationMissing:
    organization_id: UUID
    outcome: Literal["OrganizationMissing"] = field(default="OrganizationMissing", init=False)

CreateUserOutcome: TypeAlias = CreateUserCreated | CreateUserUserExists | CreateUserOrganizationMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsInput:
    title: str
    label_a: UUID
    label_b: UUID
    ticket_id: UUID
    project_id: UUID
    assignee_id: UUID
    reporter_id: UUID
    idempotency_key: str
    organization_id: UUID

OPEN_TICKET_WITH_LABELS_PLAN_HASH: Final[str] = "4000515b7b4b975c17ba6ff23c78478869cdd3f40ef2afeae80c88aefb452a48"
@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsCreated:
    ticket: Ticket
    first_link: TicketLabel
    second_link: TicketLabel
    outcome: Literal["Created"] = field(default="Created", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsLinkExists:
    label_id: UUID
    ticket_id: UUID
    outcome: Literal["LinkExists"] = field(default="LinkExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsLabelMissing:
    label_id: UUID
    outcome: Literal["LabelMissing"] = field(default="LabelMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsTicketExists:
    ticket_id: UUID
    outcome: Literal["TicketExists"] = field(default="TicketExists", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsProjectMissing:
    project_id: UUID
    outcome: Literal["ProjectMissing"] = field(default="ProjectMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsAssigneeMissing:
    user_id: UUID
    outcome: Literal["AssigneeMissing"] = field(default="AssigneeMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class OpenTicketWithLabelsReporterMissing:
    user_id: UUID
    outcome: Literal["ReporterMissing"] = field(default="ReporterMissing", init=False)

OpenTicketWithLabelsOutcome: TypeAlias = OpenTicketWithLabelsCreated | OpenTicketWithLabelsLinkExists | OpenTicketWithLabelsLabelMissing | OpenTicketWithLabelsTicketExists | OpenTicketWithLabelsProjectMissing | OpenTicketWithLabelsAssigneeMissing | OpenTicketWithLabelsReporterMissing

@dataclass(frozen=True, slots=True, kw_only=True)
class SwapMemberRolesInput:
    role_a: str
    role_b: str
    user_a: UUID
    user_b: UUID
    project_id: UUID
    idempotency_key: str
    organization_id: UUID

SWAP_MEMBER_ROLES_PLAN_HASH: Final[str] = "0b4e799a310aeca5c4c62a7eaa584d6b45d15013eb4cbaa9265460045b2a9126"
@dataclass(frozen=True, slots=True, kw_only=True)
class SwapMemberRolesSwapped:
    member_a: ProjectMember
    member_b: ProjectMember
    outcome: Literal["Swapped"] = field(default="Swapped", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class SwapMemberRolesMemberAMissing:
    user_id: UUID
    outcome: Literal["MemberAMissing"] = field(default="MemberAMissing", init=False)

@dataclass(frozen=True, slots=True, kw_only=True)
class SwapMemberRolesMemberBMissing:
    user_id: UUID
    outcome: Literal["MemberBMissing"] = field(default="MemberBMissing", init=False)

SwapMemberRolesOutcome: TypeAlias = SwapMemberRolesSwapped | SwapMemberRolesMemberAMissing | SwapMemberRolesMemberBMissing

class TicketDeskClient:
    def __init__(self, transport: SyncApplicationTransport, command_attempts: AttemptBudget) -> None:
        self._transport = transport
        self._command_attempts = command_attempts

    def board_page200(self, parameters: BoardPage200Params, options: QueryOptions = QueryOptions()) -> TypedQueryResult[BoardPage200Result]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="BoardPage200", plan_hash=BOARD_PAGE200_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": BoardPage200Found,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def board_page450(self, parameters: BoardPage450Params, options: QueryOptions = QueryOptions()) -> TypedQueryResult[BoardPage450Result]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="BoardPage450", plan_hash=BOARD_PAGE450_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": BoardPage450Found,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def board_page50(self, parameters: BoardPage50Params, options: QueryOptions = QueryOptions()) -> TypedQueryResult[BoardPage50Result]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="BoardPage50", plan_hash=BOARD_PAGE50_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": BoardPage50Found,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def get_ticket(self, parameters: GetTicketParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[GetTicketResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="GetTicket", plan_hash=GET_TICKET_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": GetTicketFound,
            "NotFound": GetTicketNotFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def get_user(self, parameters: GetUserParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[GetUserResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="GetUser", plan_hash=GET_USER_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": GetUserFound,
            "NotFound": GetUserNotFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def list_comments(self, parameters: ListCommentsParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ListCommentsResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ListComments", plan_hash=LIST_COMMENTS_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ListCommentsFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def list_tickets(self, parameters: ListTicketsParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ListTicketsResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ListTickets", plan_hash=LIST_TICKETS_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ListTicketsFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def list_tickets_by_assignee(self, parameters: ListTicketsByAssigneeParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ListTicketsByAssigneeResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ListTicketsByAssignee", plan_hash=LIST_TICKETS_BY_ASSIGNEE_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ListTicketsByAssigneeFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def project_members(self, parameters: ProjectMembersParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ProjectMembersResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ProjectMembers", plan_hash=PROJECT_MEMBERS_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ProjectMembersFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def project_summary(self, parameters: ProjectSummaryParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ProjectSummaryResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ProjectSummary", plan_hash=PROJECT_SUMMARY_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ProjectSummaryFound,
            "NotFound": ProjectSummaryNotFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def ticket_page(self, parameters: TicketPageParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[TicketPageResult]:
        raw = self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="TicketPage", plan_hash=TICKET_PAGE_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": TicketPageFound,
            "NotFound": TicketPageNotFound,
            "IntegrityFailure": TicketPageIntegrityFailure,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    def add_project_member(self, input: AddProjectMemberInput) -> TypedCommandResult[AddProjectMemberOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="AddProjectMember", plan_hash=ADD_PROJECT_MEMBER_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": AddProjectMemberCreated,
            "UserMissing": AddProjectMemberUserMissing,
            "MemberExists": AddProjectMemberMemberExists,
            "ProjectMissing": AddProjectMemberProjectMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def add_project_member_batch(
        self, inputs: Sequence[AddProjectMemberInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[AddProjectMemberOutcome]:
        return self._transport._command_batch(inputs, options, self.add_project_member, progress)

    def attach_label(self, input: AttachLabelInput) -> TypedCommandResult[AttachLabelOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="AttachLabel", plan_hash=ATTACH_LABEL_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": AttachLabelCreated,
            "LinkExists": AttachLabelLinkExists,
            "LabelMissing": AttachLabelLabelMissing,
            "TicketMissing": AttachLabelTicketMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def attach_label_batch(
        self, inputs: Sequence[AttachLabelInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[AttachLabelOutcome]:
        return self._transport._command_batch(inputs, options, self.attach_label, progress)

    def close_ticket_with_comment(self, input: CloseTicketWithCommentInput) -> TypedCommandResult[CloseTicketWithCommentOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CloseTicketWithComment", plan_hash=CLOSE_TICKET_WITH_COMMENT_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Closed": CloseTicketWithCommentClosed,
            "TicketGone": CloseTicketWithCommentTicketGone,
            "AuthorMissing": CloseTicketWithCommentAuthorMissing,
            "CommentExists": CloseTicketWithCommentCommentExists,
            "TicketMissing": CloseTicketWithCommentTicketMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def close_ticket_with_comment_batch(
        self, inputs: Sequence[CloseTicketWithCommentInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CloseTicketWithCommentOutcome]:
        return self._transport._command_batch(inputs, options, self.close_ticket_with_comment, progress)

    def create_comment(self, input: CreateCommentInput) -> TypedCommandResult[CreateCommentOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateComment", plan_hash=CREATE_COMMENT_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateCommentCreated,
            "AuthorMissing": CreateCommentAuthorMissing,
            "CommentExists": CreateCommentCommentExists,
            "TicketMissing": CreateCommentTicketMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def create_comment_batch(
        self, inputs: Sequence[CreateCommentInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateCommentOutcome]:
        return self._transport._command_batch(inputs, options, self.create_comment, progress)

    def create_label(self, input: CreateLabelInput) -> TypedCommandResult[CreateLabelOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateLabel", plan_hash=CREATE_LABEL_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateLabelCreated,
            "LabelExists": CreateLabelLabelExists,
            "OrganizationMissing": CreateLabelOrganizationMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def create_label_batch(
        self, inputs: Sequence[CreateLabelInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateLabelOutcome]:
        return self._transport._command_batch(inputs, options, self.create_label, progress)

    def create_organization(self, input: CreateOrganizationInput) -> TypedCommandResult[CreateOrganizationOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateOrganization", plan_hash=CREATE_ORGANIZATION_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateOrganizationCreated,
            "OrganizationExists": CreateOrganizationOrganizationExists,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def create_organization_batch(
        self, inputs: Sequence[CreateOrganizationInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateOrganizationOutcome]:
        return self._transport._command_batch(inputs, options, self.create_organization, progress)

    def create_project(self, input: CreateProjectInput) -> TypedCommandResult[CreateProjectOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateProject", plan_hash=CREATE_PROJECT_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateProjectCreated,
            "ProjectExists": CreateProjectProjectExists,
            "OrganizationMissing": CreateProjectOrganizationMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def create_project_batch(
        self, inputs: Sequence[CreateProjectInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateProjectOutcome]:
        return self._transport._command_batch(inputs, options, self.create_project, progress)

    def create_ticket(self, input: CreateTicketInput) -> TypedCommandResult[CreateTicketOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateTicket", plan_hash=CREATE_TICKET_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateTicketCreated,
            "TicketExists": CreateTicketTicketExists,
            "ProjectMissing": CreateTicketProjectMissing,
            "AssigneeMissing": CreateTicketAssigneeMissing,
            "ReporterMissing": CreateTicketReporterMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def create_ticket_batch(
        self, inputs: Sequence[CreateTicketInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateTicketOutcome]:
        return self._transport._command_batch(inputs, options, self.create_ticket, progress)

    def create_user(self, input: CreateUserInput) -> TypedCommandResult[CreateUserOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateUser", plan_hash=CREATE_USER_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateUserCreated,
            "UserExists": CreateUserUserExists,
            "OrganizationMissing": CreateUserOrganizationMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def create_user_batch(
        self, inputs: Sequence[CreateUserInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateUserOutcome]:
        return self._transport._command_batch(inputs, options, self.create_user, progress)

    def open_ticket_with_labels(self, input: OpenTicketWithLabelsInput) -> TypedCommandResult[OpenTicketWithLabelsOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="OpenTicketWithLabels", plan_hash=OPEN_TICKET_WITH_LABELS_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": OpenTicketWithLabelsCreated,
            "LinkExists": OpenTicketWithLabelsLinkExists,
            "LabelMissing": OpenTicketWithLabelsLabelMissing,
            "TicketExists": OpenTicketWithLabelsTicketExists,
            "ProjectMissing": OpenTicketWithLabelsProjectMissing,
            "AssigneeMissing": OpenTicketWithLabelsAssigneeMissing,
            "ReporterMissing": OpenTicketWithLabelsReporterMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def open_ticket_with_labels_batch(
        self, inputs: Sequence[OpenTicketWithLabelsInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[OpenTicketWithLabelsOutcome]:
        return self._transport._command_batch(inputs, options, self.open_ticket_with_labels, progress)

    def swap_member_roles(self, input: SwapMemberRolesInput) -> TypedCommandResult[SwapMemberRolesOutcome]:
        raw = self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="SwapMemberRoles", plan_hash=SWAP_MEMBER_ROLES_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Swapped": SwapMemberRolesSwapped,
            "MemberAMissing": SwapMemberRolesMemberAMissing,
            "MemberBMissing": SwapMemberRolesMemberBMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    def swap_member_roles_batch(
        self, inputs: Sequence[SwapMemberRolesInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[SwapMemberRolesOutcome]:
        return self._transport._command_batch(inputs, options, self.swap_member_roles, progress)

class AsyncTicketDeskClient:
    def __init__(self, transport: AsyncApplicationTransport, command_attempts: AttemptBudget) -> None:
        self._transport = transport
        self._command_attempts = command_attempts

    async def board_page200(self, parameters: BoardPage200Params, options: QueryOptions = QueryOptions()) -> TypedQueryResult[BoardPage200Result]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="BoardPage200", plan_hash=BOARD_PAGE200_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": BoardPage200Found,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def board_page450(self, parameters: BoardPage450Params, options: QueryOptions = QueryOptions()) -> TypedQueryResult[BoardPage450Result]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="BoardPage450", plan_hash=BOARD_PAGE450_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": BoardPage450Found,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def board_page50(self, parameters: BoardPage50Params, options: QueryOptions = QueryOptions()) -> TypedQueryResult[BoardPage50Result]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="BoardPage50", plan_hash=BOARD_PAGE50_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": BoardPage50Found,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def get_ticket(self, parameters: GetTicketParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[GetTicketResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="GetTicket", plan_hash=GET_TICKET_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": GetTicketFound,
            "NotFound": GetTicketNotFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def get_user(self, parameters: GetUserParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[GetUserResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="GetUser", plan_hash=GET_USER_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": GetUserFound,
            "NotFound": GetUserNotFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def list_comments(self, parameters: ListCommentsParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ListCommentsResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ListComments", plan_hash=LIST_COMMENTS_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ListCommentsFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def list_tickets(self, parameters: ListTicketsParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ListTicketsResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ListTickets", plan_hash=LIST_TICKETS_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ListTicketsFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def list_tickets_by_assignee(self, parameters: ListTicketsByAssigneeParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ListTicketsByAssigneeResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ListTicketsByAssignee", plan_hash=LIST_TICKETS_BY_ASSIGNEE_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ListTicketsByAssigneeFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def project_members(self, parameters: ProjectMembersParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ProjectMembersResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ProjectMembers", plan_hash=PROJECT_MEMBERS_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ProjectMembersFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def project_summary(self, parameters: ProjectSummaryParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[ProjectSummaryResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="ProjectSummary", plan_hash=PROJECT_SUMMARY_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": ProjectSummaryFound,
            "NotFound": ProjectSummaryNotFound,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def ticket_page(self, parameters: TicketPageParams, options: QueryOptions = QueryOptions()) -> TypedQueryResult[TicketPageResult]:
        raw = await self._transport._execute_named_query(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            contract_bundle_hash=CONTRACT_BUNDLE_HASH, module_hash=QUERY_MODULE_HASH,
            query_name="TicketPage", plan_hash=TICKET_PAGE_QUERY_PLAN_HASH,
            parameters=encode_record(parameters), options=options,
        )
        outcomes = {
            "Found": TicketPageFound,
            "NotFound": TicketPageNotFound,
            "IntegrityFailure": TicketPageIntegrityFailure,
        }
        return raw._map_value(lambda value: decode_variant(outcomes, value))

    async def add_project_member(self, input: AddProjectMemberInput) -> TypedCommandResult[AddProjectMemberOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="AddProjectMember", plan_hash=ADD_PROJECT_MEMBER_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": AddProjectMemberCreated,
            "UserMissing": AddProjectMemberUserMissing,
            "MemberExists": AddProjectMemberMemberExists,
            "ProjectMissing": AddProjectMemberProjectMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def add_project_member_batch(
        self, inputs: Sequence[AddProjectMemberInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[AddProjectMemberOutcome]:
        return await self._transport._command_batch(inputs, options, self.add_project_member, progress)

    async def attach_label(self, input: AttachLabelInput) -> TypedCommandResult[AttachLabelOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="AttachLabel", plan_hash=ATTACH_LABEL_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": AttachLabelCreated,
            "LinkExists": AttachLabelLinkExists,
            "LabelMissing": AttachLabelLabelMissing,
            "TicketMissing": AttachLabelTicketMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def attach_label_batch(
        self, inputs: Sequence[AttachLabelInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[AttachLabelOutcome]:
        return await self._transport._command_batch(inputs, options, self.attach_label, progress)

    async def close_ticket_with_comment(self, input: CloseTicketWithCommentInput) -> TypedCommandResult[CloseTicketWithCommentOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CloseTicketWithComment", plan_hash=CLOSE_TICKET_WITH_COMMENT_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Closed": CloseTicketWithCommentClosed,
            "TicketGone": CloseTicketWithCommentTicketGone,
            "AuthorMissing": CloseTicketWithCommentAuthorMissing,
            "CommentExists": CloseTicketWithCommentCommentExists,
            "TicketMissing": CloseTicketWithCommentTicketMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def close_ticket_with_comment_batch(
        self, inputs: Sequence[CloseTicketWithCommentInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CloseTicketWithCommentOutcome]:
        return await self._transport._command_batch(inputs, options, self.close_ticket_with_comment, progress)

    async def create_comment(self, input: CreateCommentInput) -> TypedCommandResult[CreateCommentOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateComment", plan_hash=CREATE_COMMENT_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateCommentCreated,
            "AuthorMissing": CreateCommentAuthorMissing,
            "CommentExists": CreateCommentCommentExists,
            "TicketMissing": CreateCommentTicketMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def create_comment_batch(
        self, inputs: Sequence[CreateCommentInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateCommentOutcome]:
        return await self._transport._command_batch(inputs, options, self.create_comment, progress)

    async def create_label(self, input: CreateLabelInput) -> TypedCommandResult[CreateLabelOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateLabel", plan_hash=CREATE_LABEL_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateLabelCreated,
            "LabelExists": CreateLabelLabelExists,
            "OrganizationMissing": CreateLabelOrganizationMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def create_label_batch(
        self, inputs: Sequence[CreateLabelInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateLabelOutcome]:
        return await self._transport._command_batch(inputs, options, self.create_label, progress)

    async def create_organization(self, input: CreateOrganizationInput) -> TypedCommandResult[CreateOrganizationOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateOrganization", plan_hash=CREATE_ORGANIZATION_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateOrganizationCreated,
            "OrganizationExists": CreateOrganizationOrganizationExists,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def create_organization_batch(
        self, inputs: Sequence[CreateOrganizationInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateOrganizationOutcome]:
        return await self._transport._command_batch(inputs, options, self.create_organization, progress)

    async def create_project(self, input: CreateProjectInput) -> TypedCommandResult[CreateProjectOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateProject", plan_hash=CREATE_PROJECT_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateProjectCreated,
            "ProjectExists": CreateProjectProjectExists,
            "OrganizationMissing": CreateProjectOrganizationMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def create_project_batch(
        self, inputs: Sequence[CreateProjectInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateProjectOutcome]:
        return await self._transport._command_batch(inputs, options, self.create_project, progress)

    async def create_ticket(self, input: CreateTicketInput) -> TypedCommandResult[CreateTicketOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateTicket", plan_hash=CREATE_TICKET_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateTicketCreated,
            "TicketExists": CreateTicketTicketExists,
            "ProjectMissing": CreateTicketProjectMissing,
            "AssigneeMissing": CreateTicketAssigneeMissing,
            "ReporterMissing": CreateTicketReporterMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def create_ticket_batch(
        self, inputs: Sequence[CreateTicketInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateTicketOutcome]:
        return await self._transport._command_batch(inputs, options, self.create_ticket, progress)

    async def create_user(self, input: CreateUserInput) -> TypedCommandResult[CreateUserOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="CreateUser", plan_hash=CREATE_USER_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": CreateUserCreated,
            "UserExists": CreateUserUserExists,
            "OrganizationMissing": CreateUserOrganizationMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def create_user_batch(
        self, inputs: Sequence[CreateUserInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[CreateUserOutcome]:
        return await self._transport._command_batch(inputs, options, self.create_user, progress)

    async def open_ticket_with_labels(self, input: OpenTicketWithLabelsInput) -> TypedCommandResult[OpenTicketWithLabelsOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="OpenTicketWithLabels", plan_hash=OPEN_TICKET_WITH_LABELS_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Created": OpenTicketWithLabelsCreated,
            "LinkExists": OpenTicketWithLabelsLinkExists,
            "LabelMissing": OpenTicketWithLabelsLabelMissing,
            "TicketExists": OpenTicketWithLabelsTicketExists,
            "ProjectMissing": OpenTicketWithLabelsProjectMissing,
            "AssigneeMissing": OpenTicketWithLabelsAssigneeMissing,
            "ReporterMissing": OpenTicketWithLabelsReporterMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def open_ticket_with_labels_batch(
        self, inputs: Sequence[OpenTicketWithLabelsInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[OpenTicketWithLabelsOutcome]:
        return await self._transport._command_batch(inputs, options, self.open_ticket_with_labels, progress)

    async def swap_member_roles(self, input: SwapMemberRolesInput) -> TypedCommandResult[SwapMemberRolesOutcome]:
        raw = await self._transport._execute_command(
            contract_lineage=CONTRACT_LINEAGE, contract_version=CONTRACT_VERSION,
            command_name="SwapMemberRoles", plan_hash=SWAP_MEMBER_ROLES_PLAN_HASH,
            input=encode_record(input), attempts=self._command_attempts,
        )
        outcomes = {
            "Swapped": SwapMemberRolesSwapped,
            "MemberAMissing": SwapMemberRolesMemberAMissing,
            "MemberBMissing": SwapMemberRolesMemberBMissing,
        }
        return raw._map_outcome(lambda value: decode_variant(outcomes, value))

    async def swap_member_roles_batch(
        self, inputs: Sequence[SwapMemberRolesInput], options: CommandBatchOptions,
        progress: Callable[[CommandBatchProgress], None] | None = None,
    ) -> CommandBatchResult[SwapMemberRolesOutcome]:
        return await self._transport._command_batch(inputs, options, self.swap_member_roles, progress)
