// @generated by riffdb-query-module; do not edit.
export const QUERY_MODULE_HASH = "459c4d8733fdf33426905f6fb1eda5100683902f979b363ed3017479937f6f37" as const;
export const CONTRACT_LINEAGE = "TicketDesk" as const;
export const CONTRACT_VERSION = 1 as const;
export const CONTRACT_BUNDLE_HASH = "23e9b5b207414e2753e4d914b1b94ecd786181be08028ace9d4f3cc0b6f4944c" as const;

export interface NamedQueryRequest<P> { readonly contractLineage: typeof CONTRACT_LINEAGE; readonly contractVersion: typeof CONTRACT_VERSION; readonly contractBundleHash: typeof CONTRACT_BUNDLE_HASH; readonly moduleHash: typeof QUERY_MODULE_HASH; readonly queryName: string; readonly parameters: P; }
export interface QueryResponseIdentity { readonly contractLineage: string; readonly contractVersion: number; readonly contractBundleHash: string; readonly moduleHash: string; readonly queryName: string; }
export function acceptsIdentity<P>(request: NamedQueryRequest<P>, identity: QueryResponseIdentity): boolean {
  return identity.contractLineage === request.contractLineage
    && identity.contractVersion === request.contractVersion
    && identity.contractBundleHash === request.contractBundleHash
    && identity.moduleHash === request.moduleHash
    && identity.queryName === request.queryName;
}
export interface CommandRequest<I> { readonly commandName: string; readonly input: I; readonly idempotencyKey: string; }

export interface GetTicketParams {
  readonly organization_id: string;
  readonly ticket_id: string;
}

export interface GetTicketFound {
  readonly outcome: "Found";
  readonly ticket: { readonly ticket_id: string; readonly project_id: string; readonly title: string; readonly status: string; readonly reporter_id: string; readonly assignee_id: string };
}

export interface GetTicketNotFound {
  readonly outcome: "NotFound";
}

export type GetTicketResult = GetTicketFound | GetTicketNotFound;

export function getTicket(parameters: GetTicketParams): NamedQueryRequest<GetTicketParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "GetTicket", parameters };
}

export interface GetUserParams {
  readonly organization_id: string;
  readonly user_id: string;
}

export interface GetUserFound {
  readonly outcome: "Found";
  readonly user: { readonly user_id: string; readonly email: string; readonly display_name: string };
}

export interface GetUserNotFound {
  readonly outcome: "NotFound";
}

export type GetUserResult = GetUserFound | GetUserNotFound;

export function getUser(parameters: GetUserParams): NamedQueryRequest<GetUserParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "GetUser", parameters };
}

export interface ListCommentsParams {
  readonly organization_id: string;
  readonly ticket_id: string;
  readonly after?: string | null;
  readonly limit?: number;
}

export interface ListCommentsFound {
  readonly outcome: "Found";
  readonly comments: ReadonlyArray<{ readonly comment_id: string; readonly body: string; readonly author_id: string; readonly created_at: string }>;
}

export type ListCommentsResult = ListCommentsFound;

export function listComments(parameters: ListCommentsParams): NamedQueryRequest<ListCommentsParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "ListComments", parameters };
}

export interface ListTicketsParams {
  readonly organization_id: string;
  readonly project_id: string;
  readonly statuses: ReadonlyArray<string>;
  readonly after?: string | null;
  readonly limit?: number;
}

export interface ListTicketsFound {
  readonly outcome: "Found";
  readonly tickets: ReadonlyArray<{ readonly ticket_id: string; readonly project_id: string; readonly title: string; readonly status: string; readonly updated_at: string; readonly reporter_id: string; readonly assignee_id: string }>;
}

export type ListTicketsResult = ListTicketsFound;

export function listTickets(parameters: ListTicketsParams): NamedQueryRequest<ListTicketsParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "ListTickets", parameters };
}

export interface ListTicketsByAssigneeParams {
  readonly organization_id: string;
  readonly assignee_id: string;
  readonly statuses: ReadonlyArray<string>;
  readonly after?: string | null;
  readonly limit?: number;
}

export interface ListTicketsByAssigneeFound {
  readonly outcome: "Found";
  readonly tickets: ReadonlyArray<{ readonly ticket_id: string; readonly project_id: string; readonly title: string; readonly status: string; readonly updated_at: string; readonly reporter_id: string; readonly assignee_id: string }>;
}

export type ListTicketsByAssigneeResult = ListTicketsByAssigneeFound;

export function listTicketsByAssignee(parameters: ListTicketsByAssigneeParams): NamedQueryRequest<ListTicketsByAssigneeParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "ListTicketsByAssignee", parameters };
}

export interface ProjectMembersParams {
  readonly organization_id: string;
  readonly project_id: string;
  readonly after?: string | null;
}

export interface ProjectMembersFound {
  readonly outcome: "Found";
  readonly members: ReadonlyArray<{ readonly user_id: string; readonly role: string }>;
}

export type ProjectMembersResult = ProjectMembersFound;

export function projectMembers(parameters: ProjectMembersParams): NamedQueryRequest<ProjectMembersParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "ProjectMembers", parameters };
}

export interface ProjectSummaryParams {
  readonly organization_id: string;
  readonly project_id: string;
  readonly status: string;
}

export interface ProjectSummaryFound {
  readonly outcome: "Found";
  readonly project: { readonly project_id: string; readonly name: string };
  readonly recent_tickets: ReadonlyArray<{ readonly ticket_id: string; readonly title: string; readonly status: string; readonly updated_at: string }>;
}

export interface ProjectSummaryNotFound {
  readonly outcome: "NotFound";
}

export type ProjectSummaryResult = ProjectSummaryFound | ProjectSummaryNotFound;

export function projectSummary(parameters: ProjectSummaryParams): NamedQueryRequest<ProjectSummaryParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "ProjectSummary", parameters };
}

export interface TicketPageParams {
  readonly organization_id: string;
  readonly ticket_id: string;
  readonly comments_after?: string | null;
}

export interface TicketPageFound {
  readonly outcome: "Found";
  readonly ticket: { readonly ticket_id: string; readonly project_id: string; readonly title: string; readonly status: string; readonly created_at: string; readonly updated_at: string };
  readonly project: { readonly project_id: string; readonly name: string };
  readonly organization: { readonly organization_id: string; readonly name: string };
  readonly reporter: { readonly user_id: string; readonly display_name: string };
  readonly assignee: { readonly user_id: string; readonly display_name: string } | null;
  readonly comments: ReadonlyArray<{ readonly comment_id: string; readonly body: string; readonly author_id: string; readonly created_at: string }>;
  readonly labels: ReadonlyArray<{ readonly label_id: string; readonly name: string }>;
}

export interface TicketPageNotFound {
  readonly outcome: "NotFound";
}

export interface TicketPageIntegrityFailure {
  readonly outcome: "IntegrityFailure";
}

export type TicketPageResult = TicketPageFound | TicketPageNotFound | TicketPageIntegrityFailure;

export function ticketPage(parameters: TicketPageParams): NamedQueryRequest<TicketPageParams> {
  return { contractLineage: CONTRACT_LINEAGE, contractVersion: CONTRACT_VERSION, contractBundleHash: CONTRACT_BUNDLE_HASH, moduleHash: QUERY_MODULE_HASH, queryName: "TicketPage", parameters };
}

export interface AddProjectMemberInput {
  readonly role: string;
  readonly user_id: string;
  readonly project_id: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function addProjectMember(input: AddProjectMemberInput, idempotencyKey: string): CommandRequest<AddProjectMemberInput> {
  return { commandName: "AddProjectMember", input, idempotencyKey };
}

export interface AttachLabelInput {
  readonly label_id: string;
  readonly ticket_id: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function attachLabel(input: AttachLabelInput, idempotencyKey: string): CommandRequest<AttachLabelInput> {
  return { commandName: "AttachLabel", input, idempotencyKey };
}

export interface CreateCommentInput {
  readonly body: string;
  readonly author_id: string;
  readonly ticket_id: string;
  readonly comment_id: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function createComment(input: CreateCommentInput, idempotencyKey: string): CommandRequest<CreateCommentInput> {
  return { commandName: "CreateComment", input, idempotencyKey };
}

export interface CreateLabelInput {
  readonly name: string;
  readonly label_id: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function createLabel(input: CreateLabelInput, idempotencyKey: string): CommandRequest<CreateLabelInput> {
  return { commandName: "CreateLabel", input, idempotencyKey };
}

export interface CreateOrganizationInput {
  readonly name: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function createOrganization(input: CreateOrganizationInput, idempotencyKey: string): CommandRequest<CreateOrganizationInput> {
  return { commandName: "CreateOrganization", input, idempotencyKey };
}

export interface CreateProjectInput {
  readonly name: string;
  readonly project_id: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function createProject(input: CreateProjectInput, idempotencyKey: string): CommandRequest<CreateProjectInput> {
  return { commandName: "CreateProject", input, idempotencyKey };
}

export interface CreateTicketInput {
  readonly title: string;
  readonly status: string;
  readonly ticket_id: string;
  readonly project_id: string;
  readonly assignee_id: string;
  readonly reporter_id: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function createTicket(input: CreateTicketInput, idempotencyKey: string): CommandRequest<CreateTicketInput> {
  return { commandName: "CreateTicket", input, idempotencyKey };
}

export interface CreateUserInput {
  readonly email: string;
  readonly user_id: string;
  readonly display_name: string;
  readonly idempotency_key: string;
  readonly organization_id: string;
}

export function createUser(input: CreateUserInput, idempotencyKey: string): CommandRequest<CreateUserInput> {
  return { commandName: "CreateUser", input, idempotencyKey };
}

