[package]
name = "riffdb-query-module"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
riffdb-contract-ir = { version = "0.1.0", path = "../riffdb-contract-ir", default-features = false }
riffdb-contract-syntax = { version = "0.1.0", path = "../riffdb-contract-syntax", default-features = false }
riffdb-query-compiler = { version = "0.1.0", path = "../riffdb-query-compiler", default-features = false }
riffdb-query-ir = { version = "0.1.0", path = "../riffdb-query-ir", default-features = false }
riffdb-riffql-syntax = { version = "0.1.0", path = "../riffdb-riffql-syntax", default-features = false }
riffdb-types = { version = "0.1.0", path = "../riffdb-types", default-features = false }
serde_json = { version = "=1.0.150", default-features = false, features = ["std"] }

[dev-dependencies]
riffdb-contract-compiler = { version = "0.1.0", path = "../riffdb-contract-compiler", default-features = false }

[[example]]
name = "generate_clients"
required-features = []

[lints]
workspace = true
