[package]
name = "riffdb-storage-redb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
redb = { version = "=4.1.0", default-features = false }
riffdb-storage-api = { version = "0.1.0", path = "../riffdb-storage-api" }
riffdb-types = { version = "0.1.0", path = "../riffdb-types" }

[[test]]
name = "storage_recovery_matrix"
path = "../../tests/storage_recovery/storage_recovery_matrix.rs"

[lints]
workspace = true
