[package]
name = "riffdb-api-exclusive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tokio = { version = "=1.52.0", default-features = false, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "=1.52.0", default-features = false, features = ["io-util", "macros", "rt"] }

[lints]
workspace = true
