#![forbid(unsafe_code)]

//! WP-751 generated-validation compatibility and ownership proof.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use riffdb_operation_registry::{BoundTarget, OPERATIONS, declaration};
use riffdb_types::ServiceOperationV1;

const GENERATED: &str = include_str!("../src/generated/public_validation.rs");
const FROZEN: &str = include_str!("../../../fixtures/proto/public-validation-v1.rs.in");
const WRAPPER: &str = include_str!("../src/public_message.rs");

fn visit_hand_written_rust(path: &Path, files: &mut Vec<std::path::PathBuf>) {
    for entry in fs::read_dir(path).expect("read source directory") {
        let entry = entry.expect("read source entry");
        let entry_path = entry.path();
        if entry_path.is_dir() {
            if entry.file_name() != "generated" {
                visit_hand_written_rust(&entry_path, files);
            }
        } else if entry_path
            .extension()
            .is_some_and(|extension| extension == "rs")
        {
            files.push(entry_path);
        }
    }
}

#[test]
fn every_public_operation_has_exactly_one_registry_declaration() {
    assert_eq!(OPERATIONS.len(), ServiceOperationV1::ALL.len());
    let declared = OPERATIONS
        .iter()
        .map(|entry| entry.operation)
        .collect::<BTreeSet<_>>();
    assert_eq!(declared, ServiceOperationV1::ALL.into_iter().collect());
    for operation in ServiceOperationV1::ALL {
        assert_eq!(declaration(operation).operation, operation);
    }

    let mut files = Vec::new();
    visit_hand_written_rust(
        &Path::new(env!("CARGO_MANIFEST_DIR")).join("src"),
        &mut files,
    );
    for path in files {
        let source = fs::read_to_string(&path).expect("read hand-written Rust source");
        for (offset, _) in source.match_indices("fn validate_") {
            let suffix = &source[offset..source.len().min(offset + 160)];
            assert!(
                !suffix.contains("_exchange"),
                "hand-written exchange validation remains outside src/generated: {}",
                path.display()
            );
        }
    }
}

#[test]
fn generated_adapters_reproduce_frozen_public_fixtures_byte_for_byte() {
    assert!(GENERATED.starts_with("// @generated by scripts/generate-operation-adapters"));
    let after_header = GENERATED
        .strip_prefix("// @generated by scripts/generate-operation-adapters; DO NOT EDIT.\n\n")
        .expect("generated header");
    let (_, generated_body) = FROZEN
        .split_once("\n\n")
        .expect("frozen module context documentation");
    assert!(after_header.starts_with(generated_body));
    assert_eq!(
        GENERATED.match_indices("pub fn validate_").count(),
        FROZEN.match_indices("pub fn validate_").count(),
        "generation lost a public validation exchange"
    );
    assert_eq!(
        WRAPPER.trim(),
        "include!(\"generated/public_validation.rs\");",
        "the hand-written module regained validation ownership"
    );
}

#[test]
fn generated_inventory_covers_every_registry_operation_in_tag_order() {
    assert_eq!(riffdb_proto::GENERATED_OPERATION_REGISTRY_VERSION, 1);
    assert_eq!(riffdb_proto::GENERATED_PUBLIC_OPERATION_COUNT, 62);
    assert_eq!(riffdb_proto::GENERATED_PUBLIC_VALIDATION_MESSAGES.len(), 62);
    let stream = &riffdb_proto::GENERATED_PUBLIC_VALIDATION_MESSAGES[60];
    assert_eq!((stream.tag, stream.operation), (0x3d, "StreamChangelog"));
    assert_eq!(
        (stream.request, stream.response),
        (
            "riffdb.v1.StreamChangelogRequest",
            "riffdb.v1.StreamChangelogResponse"
        )
    );
    assert_eq!((stream.request_fields, stream.response_fields), (13, 6));
    assert_eq!(
        (stream.request_bytes, stream.response_bytes),
        (1024, 32 * 1024 * 1024 + 1024)
    );
    let promotion = &riffdb_proto::GENERATED_PUBLIC_VALIDATION_MESSAGES[61];
    assert_eq!(
        (promotion.tag, promotion.operation),
        (0x3e, "PromoteFollower")
    );
    assert_eq!(
        (promotion.request, promotion.response),
        (
            "riffdb.v1.PromoteFollowerRequest",
            "riffdb.v1.PromoteFollowerResponse"
        )
    );
    assert_eq!(
        (promotion.request_fields, promotion.response_fields),
        (5, 1)
    );
    for (index, entry) in riffdb_proto::GENERATED_PUBLIC_VALIDATION_MESSAGES
        .iter()
        .enumerate()
    {
        assert_eq!(usize::from(entry.tag), index + 1);
        assert!(!entry.operation.is_empty());
        assert!(entry.request.starts_with("riffdb."));
        assert!(entry.response.starts_with("riffdb."));
        let declaration = declaration(ServiceOperationV1::ALL[index]);
        let request_bound = declaration
            .bounds
            .iter()
            .find(|bound| bound.target == BoundTarget::EncodedRequestBytes)
            .expect("request bound");
        let response_bound = declaration
            .bounds
            .iter()
            .find(|bound| bound.target == BoundTarget::EncodedResponseBytes)
            .expect("response bound");
        assert_eq!(entry.request_bytes, request_bound.maximum);
        assert_eq!(entry.response_bytes, response_bound.maximum);
    }
}
