[package]
name = "riffdb-conflict"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
loom = []
shuttle = []

[dependencies]
riffdb-observability = { version = "0.1.0", path = "../riffdb-observability", default-features = false }
riffdb-types = { version = "0.1.0", path = "../riffdb-types" }

[dev-dependencies]
loom = { version = "0.7.2", default-features = false }
shuttle = { version = "0.9.1", default-features = false }

[lints]
workspace = true
