// @generated by riffdb-query-module; do not edit.
use std::collections::BTreeMap;
use riffdb_client_rust::generated::{GeneratedCommand, GeneratedCommandError, GeneratedQuery};
use riffdb_client_rust::{ApplicationCardinality, ApplicationClientError, ApplicationContract, ApplicationUuid, CanonicalVector, ApplicationRecord, ApplicationSessionIdentity, ApplicationValue, AttemptBudget, CallMetadata, GeneratedBatchError, GeneratedBatchOptions, GeneratedBatchProgress, GeneratedBatchResult, IdempotentCommand, NamedQuery, NamedQueryResult, StableApplicationClient, TypedCommandResult, TypedQueryResult, VectorStateInspection, VectorStateInspectionKind, VectorStateInspectionResult, v1};
pub use riffdb_client_rust::QueryOptions;
use riffdb_client_rust::v1::value::Kind as WireKind;

pub const QUERY_MODULE_HASH: [u8; 32] = [0x9c, 0x32, 0x4f, 0xa8, 0xc4, 0xbe, 0xd1, 0x28, 0xaf, 0xe5, 0xd0, 0xbb, 0x04, 0x2c, 0xec, 0x3e, 0x4c, 0xd3, 0xf8, 0x2a, 0x5a, 0xa4, 0x27, 0x58, 0xcf, 0x1a, 0x76, 0xcc, 0x80, 0xb5, 0xc4, 0xbe];
pub const CONTRACT_LINEAGE: &str = "VectorDocuments";
pub const CONTRACT_VERSION: u64 = 1;

pub const CONTRACT_BUNDLE_HASH: [u8; 32] = [0x4a, 0xdd, 0xba, 0xd0, 0x4a, 0xed, 0x32, 0x94, 0x6d, 0xc9, 0x8c, 0x91, 0x56, 0x1b, 0x58, 0x64, 0x46, 0x56, 0x18, 0xb7, 0x87, 0x7e, 0xee, 0xb5, 0xd5, 0x95, 0x26, 0x92, 0xdb, 0x19, 0x25, 0x06];

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DecimalValue {
    pub coefficient_twos_complement: Vec<u8>,
    pub scale: u32,
    pub precision: Option<u32>,
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MoneyValue {
    pub currency: String,
    pub amount: DecimalValue,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TimestampValue {
    pub seconds: i64,
    pub nanos: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SimilarDocumentsParams {
    pub organization_id: String,
    pub query_vector: CanonicalVector,
    pub k: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SimilarDocumentsFoundDocuments {
    pub organization_id: String,
    pub document_id: String,
    pub title: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SimilarDocumentsFound {
    pub documents: Vec<SimilarDocumentsFoundDocuments>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum SimilarDocumentsResult {
    Found(Box<SimilarDocumentsFound>),
}

pub const SIMILAR_DOCUMENTS_QUERY_PLAN_HASH: [u8; 32] = [0x29, 0x09, 0x10, 0x01, 0xab, 0xb4, 0x23, 0x80, 0xa7, 0xf4, 0xf5, 0xd3, 0x8b, 0x2f, 0xa7, 0xb5, 0xde, 0xfd, 0x8c, 0xa8, 0xe9, 0xf9, 0xae, 0x51, 0x6c, 0xfc, 0x9b, 0x1d, 0x6e, 0x69, 0x4b, 0x49];
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SimilarDocumentsQuery(pub SimilarDocumentsParams);
impl GeneratedQuery for SimilarDocumentsQuery {
    type Output = SimilarDocumentsResult;

    fn named_query(self, options: QueryOptions) -> Result<NamedQuery, ApplicationClientError> {
        let mut parameters = BTreeMap::new();
        parameters.insert("organization_id".to_owned(), ApplicationValue::Uuid(ApplicationUuid::from_text(self.0.organization_id)?));
        parameters.insert("query_vector".to_owned(), ApplicationValue::Vector(self.0.query_vector));
        parameters.insert("k".to_owned(), ApplicationValue::U64(self.0.k));
        NamedQuery::new(
            ApplicationContract::Exact {
                lineage: CONTRACT_LINEAGE.to_owned(),
                version: CONTRACT_VERSION,
                bundle_hash: Some(CONTRACT_BUNDLE_HASH),
            },
            "SimilarDocuments",
            Some(QUERY_MODULE_HASH),
            parameters,
            None,
        )?.expect_plan_hash(SIMILAR_DOCUMENTS_QUERY_PLAN_HASH).with_options(options)
    }

    fn decode_result(mut response: NamedQueryResult) -> Result<Self::Output, ApplicationClientError> {
        let outcome = response.outcome.clone();
        match outcome.as_str() {
            "Found" => {
                let decoded = SimilarDocumentsFound {
                    documents: many_result_records(take_result_field(&mut response.fields, "documents")?)?.into_iter().map(decode_similar_documents_found_documents_record).collect::<Result<Vec<_>, _>>()?,
                };
                if !response.fields.is_empty() { return Err(ApplicationClientError::InvalidResponse); }
                Ok(SimilarDocumentsResult::Found(Box::new(decoded)))
            },
            _ => Err(ApplicationClientError::InvalidResponse),
        }
    }
}

fn decode_similar_documents_found_documents_record(mut record: ApplicationRecord) -> Result<SimilarDocumentsFoundDocuments, ApplicationClientError> {
    let value = SimilarDocumentsFoundDocuments {
        organization_id: application_uuid(take_application_value(&mut record.fields, "organization_id")?)?,
        document_id: application_uuid(take_application_value(&mut record.fields, "document_id")?)?,
        title: application_string(take_application_value(&mut record.fields, "title")?)?,
    };
    if !record.fields.is_empty() { return Err(ApplicationClientError::InvalidResponse); }
    Ok(value)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Document {
    pub body: String,
    pub title: String,
    pub embedding: CanonicalVector,
    pub document_id: String,
    pub organization_id: String,
}

fn encode_document_entity(value: &Document) -> Result<v1::Value, GeneratedCommandError> {
    let fields = vec![
        v1::ValueField { field_id: Some(1), name: String::new(), value: Some(wire_string(Clone::clone(&value.body))) },
        v1::ValueField { field_id: Some(2), name: String::new(), value: Some(wire_string(Clone::clone(&value.title))) },
        v1::ValueField { field_id: Some(3), name: String::new(), value: Some(wire_vector(&value.embedding, 4)?) },
        v1::ValueField { field_id: Some(4), name: String::new(), value: Some(wire_uuid(&value.document_id)?) },
        v1::ValueField { field_id: Some(5), name: String::new(), value: Some(wire_uuid(&value.organization_id)?) },
    ];
    Ok(v1::Value { kind: Some(WireKind::RecordValue(v1::ValueRecord { fields })) })
}

fn decode_document_entity(value: v1::Value) -> Result<Document, GeneratedCommandError> {
    let mut fields = wire_record_fields(value)?;
    let entity = Document {
        body: decode_wire_string(take_wire_field(&mut fields, 1)?)?,
        title: decode_wire_string(take_wire_field(&mut fields, 2)?)?,
        embedding: decode_wire_vector(take_wire_field(&mut fields, 3)?, 4)?,
        document_id: decode_wire_uuid(take_wire_field(&mut fields, 4)?)?,
        organization_id: decode_wire_uuid(take_wire_field(&mut fields, 5)?)?,
    };
    if !fields.is_empty() { return Err(GeneratedCommandError::InvalidOutcomeShape); }
    Ok(entity)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateEmbeddedDocumentInput {
    pub body: String,
    pub title: String,
    pub embedding: CanonicalVector,
    pub document_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
    pub submitted_model: String,
    pub submitted_version: String,
}

impl CreateEmbeddedDocumentInput {
    pub const EMBEDDING_MODEL_IDENTITY: &'static str = "embed-v1";
    pub const EMBEDDING_MODEL_VERSION: &'static str = "2026-08-21";
    pub fn for_embedding(body: String, title: String, embedding: CanonicalVector, document_id: String, idempotency_key: String, organization_id: String) -> Self {
        Self {
            body,
            title,
            embedding,
            document_id,
            idempotency_key,
            organization_id,
            submitted_model: Self::EMBEDDING_MODEL_IDENTITY.to_owned(),
            submitted_version: Self::EMBEDDING_MODEL_VERSION.to_owned(),
        }
    }
    pub fn embedding_model_identity(&self) -> &str { &self.submitted_model }
    pub fn embedding_model_version(&self) -> &str { &self.submitted_version }
}

#[allow(clippy::large_enum_variant)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CreateEmbeddedDocumentOutcome {
    Created {
        document: Document,
    },

    DocumentExists {
        document_id: String,
    },
}

const CREATE_EMBEDDED_DOCUMENT_PLAN_HASH: [u8; 32] = [0x3e, 0x37, 0x5f, 0xf0, 0x01, 0xcc, 0xfc, 0x7f, 0x02, 0x21, 0x6e, 0xd1, 0xc6, 0x15, 0x63, 0xc5, 0x09, 0x1f, 0x9f, 0x3e, 0x06, 0xb7, 0xf9, 0x26, 0xd9, 0x20, 0x5e, 0x25, 0x32, 0x88, 0x4c, 0x56];
impl GeneratedCommand for CreateEmbeddedDocumentInput {
    type Outcome = CreateEmbeddedDocumentOutcome;

    fn idempotent_command(&self) -> Result<IdempotentCommand, GeneratedCommandError> {

        let fields = vec![
            wire_named_field("body", wire_string(Clone::clone(&self.body))),
            wire_named_field("title", wire_string(Clone::clone(&self.title))),
            wire_named_field("embedding", wire_vector(&self.embedding, 4)?),
            wire_named_field("document_id", wire_uuid(&self.document_id)?),
            wire_named_field("idempotency_key", wire_string(Clone::clone(&self.idempotency_key))),
            wire_named_field("organization_id", wire_uuid(&self.organization_id)?),
            wire_named_field("submitted_model", wire_string(Clone::clone(&self.submitted_model))),
            wire_named_field("submitted_version", wire_string(Clone::clone(&self.submitted_version))),
        ];
        IdempotentCommand::new("CreateEmbeddedDocument", Some(CONTRACT_VERSION), wire_record(fields)).map_err(Into::into)
    }

    fn outcome_request(&self, request_id: riffdb_client_rust::RequestId) -> Result<v1::GetOutcomeRequest, GeneratedCommandError> {
        Ok(v1::GetOutcomeRequest {
            request_id: request_id.into_bytes().to_vec(),
            contract_lineage: CONTRACT_LINEAGE.to_owned(),
            command_name: "CreateEmbeddedDocument".to_owned(),
            idempotency_key: self.idempotency_key.clone(),
            outcome_uri: None,
        })
    }

    fn decode_outcome(&self, response: &v1::ExecuteCommandResponse) -> Result<Self::Outcome, GeneratedCommandError> {
        let mut fields = wire_outcome_fields(response, &CREATE_EMBEDDED_DOCUMENT_PLAN_HASH)?;
        match response.outcome_type.as_str() {
            "Created" => {
                let outcome = Self::Outcome::Created {
                    document: decode_document_entity(take_wire_field(&mut fields, 1)?)?,
                };
                if !fields.is_empty() { return Err(GeneratedCommandError::InvalidOutcomeShape); }
                Ok(outcome)
            },
            "DocumentExists" => {
                let outcome = Self::Outcome::DocumentExists {
                    document_id: decode_wire_uuid(take_wire_field(&mut fields, 1)?)?,
                };
                if !fields.is_empty() { return Err(GeneratedCommandError::InvalidOutcomeShape); }
                Ok(outcome)
            },
            _ => Err(GeneratedCommandError::InvalidOutcomeShape),
        }
    }
}

pub struct VectorDocumentsClient {
    client: StableApplicationClient,
    metadata: CallMetadata,
    command_attempts: AttemptBudget,
}
impl VectorDocumentsClient {
    pub const fn new(client: StableApplicationClient, metadata: CallMetadata, command_attempts: AttemptBudget) -> Self {
        Self { client, metadata, command_attempts }
    }

    /// Selects ADR-0127's optional bounded application-operation session for this exact generated identity.
    pub async fn open_bounded_session(&mut self, application_lock_hash: [u8; 32]) -> Result<(), ApplicationClientError> {
        let identity = ApplicationSessionIdentity::new(CONTRACT_LINEAGE.to_owned(), CONTRACT_VERSION, CONTRACT_BUNDLE_HASH, vec![QUERY_MODULE_HASH], application_lock_hash, 128)
            .map_err(|_| ApplicationClientError::InvalidInput)?;
        self.client.open_bounded_session(identity, &self.metadata).await
    }
    /// Reports the application transport selected by this generated client.
    #[must_use]
    pub const fn bounded_session_enabled(&self) -> bool { self.client.bounded_session_enabled() }
    /// Closes the optional bounded session and returns to unary transport.
    pub fn close_bounded_session(&mut self) { self.client.close_bounded_session(); }

    /// Executes the generated `SimilarDocuments` named query.
    pub async fn similar_documents(&mut self, parameters: SimilarDocumentsParams) -> Result<SimilarDocumentsResult, ApplicationClientError> {
        Ok(self.similar_documents_with_options(parameters, QueryOptions::new()).await?.value)
    }
    /// Executes `SimilarDocuments` against a snapshot at or after the supplied command commit.
    pub async fn similar_documents_after_commit(&mut self, parameters: SimilarDocumentsParams, commit_sequence: u64) -> Result<TypedQueryResult<SimilarDocumentsResult>, ApplicationClientError> {
        self.similar_documents_with_options(parameters, QueryOptions::new().read_after_commit(commit_sequence)).await
    }
    /// Executes `SimilarDocuments` with generated pagination or read-fence options.
    pub async fn similar_documents_with_options(&mut self, parameters: SimilarDocumentsParams, options: QueryOptions) -> Result<TypedQueryResult<SimilarDocumentsResult>, ApplicationClientError> {
        self.client.execute_generated_query(SimilarDocumentsQuery(parameters), options, &self.metadata).await
    }

    pub async fn create_embedded_document(&mut self, input: CreateEmbeddedDocumentInput) -> Result<TypedCommandResult<CreateEmbeddedDocumentOutcome>, ApplicationClientError> {
        self.client.execute_generated_command(&input, self.command_attempts, &self.metadata).await.map_err(Into::into)
    }

    pub async fn create_embedded_document_batch(&self, inputs: Vec<CreateEmbeddedDocumentInput>, options: GeneratedBatchOptions) -> Result<GeneratedBatchResult<CreateEmbeddedDocumentOutcome>, GeneratedBatchError> {
        self.client.execute_generated_command_batch(inputs, options, self.command_attempts, &self.metadata).await
    }

    pub async fn create_embedded_document_batch_with_progress<F>(&self, inputs: Vec<CreateEmbeddedDocumentInput>, options: GeneratedBatchOptions, progress: F) -> Result<GeneratedBatchResult<CreateEmbeddedDocumentOutcome>, GeneratedBatchError>
    where
        F: FnMut(GeneratedBatchProgress),
    {
        self.client.execute_generated_command_batch_with_progress(inputs, options, self.command_attempts, &self.metadata, progress).await
    }

    /// Inspects authoritative `Document.embedding` staleness state.
    pub async fn inspect_document_embedding_staleness(&mut self, partition: String, limit: u32, cursor: Option<Vec<u8>>) -> Result<VectorStateInspectionResult, ApplicationClientError> {
        let request = VectorStateInspection::new(
            ApplicationContract::Exact { lineage: CONTRACT_LINEAGE.to_owned(), version: CONTRACT_VERSION, bundle_hash: Some(CONTRACT_BUNDLE_HASH) },
            "Document", "embedding", ApplicationValue::Uuid(ApplicationUuid::from_text(partition)?), VectorStateInspectionKind::Stale, limit,
        );
        let request = match cursor { Some(cursor) => request.after(cursor), None => request };
        self.client.inspect_vector_state(request, &self.metadata).await
    }

    /// Inspects authoritative `Document.embedding` model_versions state.
    pub async fn inspect_document_embedding_model_versions(&mut self, partition: String, limit: u32, cursor: Option<Vec<u8>>) -> Result<VectorStateInspectionResult, ApplicationClientError> {
        let request = VectorStateInspection::new(
            ApplicationContract::Exact { lineage: CONTRACT_LINEAGE.to_owned(), version: CONTRACT_VERSION, bundle_hash: Some(CONTRACT_BUNDLE_HASH) },
            "Document", "embedding", ApplicationValue::Uuid(ApplicationUuid::from_text(partition)?), VectorStateInspectionKind::OutdatedModel, limit,
        );
        let request = match cursor { Some(cursor) => request.after(cursor), None => request };
        self.client.inspect_vector_state(request, &self.metadata).await
    }

}

fn take_result_field(fields: &mut BTreeMap<String, riffdb_client_rust::ApplicationResultField>, name: &str) -> Result<riffdb_client_rust::ApplicationResultField, ApplicationClientError> {
    fields.remove(name).ok_or(ApplicationClientError::InvalidResponse)
}
fn one_result_record(field: riffdb_client_rust::ApplicationResultField) -> Result<ApplicationRecord, ApplicationClientError> {
    if field.cardinality != ApplicationCardinality::One || field.records.len() != 1 { return Err(ApplicationClientError::InvalidResponse); }
    field.records.into_iter().next().ok_or(ApplicationClientError::InvalidResponse)
}
fn optional_result_record(field: riffdb_client_rust::ApplicationResultField) -> Result<Option<ApplicationRecord>, ApplicationClientError> {
    if field.cardinality != ApplicationCardinality::Maybe || field.records.len() > 1 { return Err(ApplicationClientError::InvalidResponse); }
    Ok(field.records.into_iter().next())
}
fn many_result_records(field: riffdb_client_rust::ApplicationResultField) -> Result<Vec<ApplicationRecord>, ApplicationClientError> {
    if field.cardinality != ApplicationCardinality::Many { return Err(ApplicationClientError::InvalidResponse); }
    Ok(field.records)
}
fn take_application_value(fields: &mut BTreeMap<String, ApplicationValue>, name: &str) -> Result<ApplicationValue, ApplicationClientError> {
    fields.remove(name).ok_or(ApplicationClientError::InvalidResponse)
}
fn application_bool(value: ApplicationValue) -> Result<bool, ApplicationClientError> { if let ApplicationValue::Bool(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_i64(value: ApplicationValue) -> Result<i64, ApplicationClientError> { if let ApplicationValue::I64(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_u64(value: ApplicationValue) -> Result<u64, ApplicationClientError> { if let ApplicationValue::U64(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_string(value: ApplicationValue) -> Result<String, ApplicationClientError> { if let ApplicationValue::String(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_uuid(value: ApplicationValue) -> Result<String, ApplicationClientError> { if let ApplicationValue::Uuid(value) = value { Ok(value.into_string()) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_enum(value: ApplicationValue) -> Result<String, ApplicationClientError> { if let ApplicationValue::Enum(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_bytes(value: ApplicationValue) -> Result<Vec<u8>, ApplicationClientError> { if let ApplicationValue::Bytes(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_date(value: ApplicationValue) -> Result<i32, ApplicationClientError> { if let ApplicationValue::Date(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_timestamp(value: ApplicationValue) -> Result<TimestampValue, ApplicationClientError> { if let ApplicationValue::Timestamp { seconds, nanos } = value { Ok(TimestampValue { seconds, nanos }) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_decimal(value: ApplicationValue) -> Result<DecimalValue, ApplicationClientError> { if let ApplicationValue::Decimal { coefficient_twos_complement, scale, precision } = value { Ok(DecimalValue { coefficient_twos_complement, scale, precision }) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_list(value: ApplicationValue) -> Result<Vec<ApplicationValue>, ApplicationClientError> { if let ApplicationValue::List(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn application_record(value: ApplicationValue) -> Result<ApplicationRecord, ApplicationClientError> { if let ApplicationValue::Record(fields) = value { Ok(ApplicationRecord { entity: String::new(), fields }) } else { Err(ApplicationClientError::InvalidResponse) } }
fn wire_named_field(name: &str, value: v1::Value) -> v1::ValueField { v1::ValueField { field_id: None, name: name.to_owned(), value: Some(value) } }
fn wire_record(mut fields: Vec<v1::ValueField>) -> v1::Value {
    fields.sort_by(|left, right| left.name.cmp(&right.name));
    v1::Value { kind: Some(WireKind::RecordValue(v1::ValueRecord { fields })) }
}
fn wire_null() -> v1::Value { v1::Value { kind: Some(WireKind::NullValue(v1::NullValue::NullValue as i32)) } }
fn wire_string(value: String) -> v1::Value { v1::Value { kind: Some(WireKind::StringValue(value)) } }
fn wire_bool(value: bool) -> v1::Value { v1::Value { kind: Some(WireKind::BoolValue(value)) } }
fn wire_i64(value: i64) -> v1::Value { v1::Value { kind: Some(WireKind::I64Value(value)) } }
fn wire_u64(value: u64) -> v1::Value { v1::Value { kind: Some(WireKind::U64Value(value)) } }
fn wire_bytes(value: Vec<u8>) -> v1::Value { v1::Value { kind: Some(WireKind::BytesValue(value)) } }
fn wire_date(value: i32) -> v1::Value { v1::Value { kind: Some(WireKind::DateValue(v1::Date { days_since_unix_epoch: value })) } }
fn wire_timestamp(value: &TimestampValue) -> Result<v1::Value, GeneratedCommandError> { if value.nanos >= 1_000_000_000 { return Err(GeneratedCommandError::InvalidInputShape); } Ok(v1::Value { kind: Some(WireKind::TimestampValue(v1::Timestamp { seconds: value.seconds, nanos: value.nanos })) }) }
fn wire_decimal(value: &DecimalValue) -> v1::Value { v1::Value { kind: Some(WireKind::DecimalValue(v1::Decimal { coefficient_twos_complement: value.coefficient_twos_complement.clone(), scale: value.scale, precision: value.precision })) } }
fn wire_money(value: &MoneyValue, expected_currency: &str) -> Result<v1::Value, GeneratedCommandError> {
    if value.currency != expected_currency || value.amount.scale != 2 || value.amount.precision != Some(38) { return Err(GeneratedCommandError::InvalidInputShape); }
    Ok(v1::Value { kind: Some(WireKind::MoneyValue(v1::Money {
        currency: value.currency.clone(),
        amount: Some(v1::Decimal {
            coefficient_twos_complement: value.amount.coefficient_twos_complement.clone(),
            scale: value.amount.scale,
            precision: value.amount.precision,
        }),
    })) })
}
fn wire_enum(value: String) -> v1::Value { v1::Value { kind: Some(WireKind::EnumValue(v1::EnumValue { type_id: 0, variant_id: 0, name: value })) } }
fn wire_uuid(value: &str) -> Result<v1::Value, GeneratedCommandError> {
    if value.len() != 36 { return Err(GeneratedCommandError::InvalidInputShape); }
    let compact = value.bytes().filter(|byte| *byte != b'-').collect::<Vec<_>>();
    if compact.len() != 32 { return Err(GeneratedCommandError::InvalidInputShape); }
    let mut bytes = Vec::with_capacity(16);
    for pair in compact.chunks_exact(2) {
        let text = std::str::from_utf8(pair).map_err(|_| GeneratedCommandError::InvalidInputShape)?;
        bytes.push(u8::from_str_radix(text, 16).map_err(|_| GeneratedCommandError::InvalidInputShape)?);
    }
    Ok(v1::Value { kind: Some(WireKind::UuidValue(bytes)) })
}
fn wire_outcome_fields(response: &v1::ExecuteCommandResponse, plan_hash: &[u8; 32]) -> Result<BTreeMap<u32, v1::Value>, GeneratedCommandError> {
    if response.contract_version != CONTRACT_VERSION || response.plan_hash.as_slice() != plan_hash { return Err(GeneratedCommandError::InvalidOutcomeShape); }
    wire_record_fields(response.outcome.clone().ok_or(GeneratedCommandError::InvalidOutcomeShape)?)
}
fn wire_record_fields(value: v1::Value) -> Result<BTreeMap<u32, v1::Value>, GeneratedCommandError> {
    let Some(WireKind::RecordValue(record)) = value.kind else { return Err(GeneratedCommandError::InvalidOutcomeShape); };
    let mut fields = BTreeMap::new();
    for field in record.fields {
        let id = field.field_id.ok_or(GeneratedCommandError::InvalidOutcomeShape)?;
        if id == 0 || fields.insert(id, field.value.ok_or(GeneratedCommandError::InvalidOutcomeShape)?).is_some() { return Err(GeneratedCommandError::InvalidOutcomeShape); }
    }
    Ok(fields)
}
fn take_wire_field(fields: &mut BTreeMap<u32, v1::Value>, id: u32) -> Result<v1::Value, GeneratedCommandError> { fields.remove(&id).ok_or(GeneratedCommandError::InvalidOutcomeShape) }
fn decode_wire_optional<T>(value: v1::Value, decode: impl FnOnce(v1::Value) -> Result<T, GeneratedCommandError>) -> Result<Option<T>, GeneratedCommandError> {
    if matches!(value.kind.as_ref(), Some(WireKind::NullValue(_))) { Ok(None) } else { decode(value).map(Some) }
}
fn decode_wire_bool(value: v1::Value) -> Result<bool, GeneratedCommandError> { if let Some(WireKind::BoolValue(value)) = value.kind { Ok(value) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_i64(value: v1::Value) -> Result<i64, GeneratedCommandError> { if let Some(WireKind::I64Value(value)) = value.kind { Ok(value) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_u64(value: v1::Value) -> Result<u64, GeneratedCommandError> { if let Some(WireKind::U64Value(value)) = value.kind { Ok(value) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_string(value: v1::Value) -> Result<String, GeneratedCommandError> { if let Some(WireKind::StringValue(value)) = value.kind { Ok(value) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_uuid(value: v1::Value) -> Result<String, GeneratedCommandError> {
    let Some(WireKind::UuidValue(bytes)) = value.kind else { return Err(GeneratedCommandError::InvalidOutcomeShape); };
    let bytes: [u8; 16] = bytes.try_into().map_err(|_| GeneratedCommandError::InvalidOutcomeShape)?;
    Ok(ApplicationUuid::from_bytes(bytes).into_string())
}
fn decode_wire_enum(value: v1::Value) -> Result<String, GeneratedCommandError> { if let Some(WireKind::EnumValue(value)) = value.kind { if value.name.is_empty() { Err(GeneratedCommandError::InvalidOutcomeShape) } else { Ok(value.name) } } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_bytes(value: v1::Value) -> Result<Vec<u8>, GeneratedCommandError> { if let Some(WireKind::BytesValue(value)) = value.kind { Ok(value) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_date(value: v1::Value) -> Result<i32, GeneratedCommandError> { if let Some(WireKind::DateValue(value)) = value.kind { Ok(value.days_since_unix_epoch) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_timestamp(value: v1::Value) -> Result<TimestampValue, GeneratedCommandError> { if let Some(WireKind::TimestampValue(value)) = value.kind { if value.nanos < 1_000_000_000 { Ok(TimestampValue { seconds: value.seconds, nanos: value.nanos }) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_decimal(value: v1::Value) -> Result<DecimalValue, GeneratedCommandError> { if let Some(WireKind::DecimalValue(value)) = value.kind { Ok(DecimalValue { coefficient_twos_complement: value.coefficient_twos_complement, scale: value.scale, precision: value.precision }) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
fn decode_wire_money(value: v1::Value, expected_currency: &str) -> Result<MoneyValue, GeneratedCommandError> {
    let Some(WireKind::MoneyValue(value)) = value.kind else { return Err(GeneratedCommandError::InvalidOutcomeShape); };
    let amount = value.amount.ok_or(GeneratedCommandError::InvalidOutcomeShape)?;
    if value.currency != expected_currency || amount.scale != 2 || amount.precision != Some(38) { return Err(GeneratedCommandError::InvalidOutcomeShape); }
    Ok(MoneyValue { currency: value.currency, amount: DecimalValue { coefficient_twos_complement: amount.coefficient_twos_complement, scale: amount.scale, precision: amount.precision } })
}
fn application_vector(value: ApplicationValue) -> Result<CanonicalVector, ApplicationClientError> { if let ApplicationValue::Vector(value) = value { Ok(value) } else { Err(ApplicationClientError::InvalidResponse) } }
fn wire_vector(value: &CanonicalVector, dimension: u32) -> Result<v1::Value, GeneratedCommandError> { if value.dimension() != dimension { return Err(GeneratedCommandError::InvalidInputShape); } Ok(v1::Value { kind: Some(WireKind::VectorValue(v1::VectorValue { components: value.components().to_vec() })) }) }
fn decode_wire_vector(value: v1::Value, dimension: u32) -> Result<CanonicalVector, GeneratedCommandError> { if let Some(WireKind::VectorValue(value)) = value.kind { let vector = CanonicalVector::new(value.components).map_err(|_| GeneratedCommandError::InvalidOutcomeShape)?; if vector.dimension() != dimension { return Err(GeneratedCommandError::InvalidOutcomeShape); } Ok(vector) } else { Err(GeneratedCommandError::InvalidOutcomeShape) } }
