// @generated by riffdb-query-module; do not edit.

pub const QUERY_MODULE_HASH: [u8; 32] = [0x7b, 0xef, 0x47, 0x1a, 0x9e, 0xeb, 0xc9, 0xc0, 0x37, 0x4d, 0x73, 0xbd, 0x0a, 0x62, 0xc1, 0x60, 0x35, 0x8f, 0xde, 0x53, 0xbd, 0xb5, 0x02, 0x78, 0x8d, 0x9d, 0x3b, 0x02, 0x6b, 0xad, 0xf6, 0x11];
pub const CONTRACT_LINEAGE: &str = "TicketDesk";
pub const CONTRACT_VERSION: u64 = 1;

pub const CONTRACT_BUNDLE_HASH: [u8; 32] = [0xe4, 0x11, 0x62, 0x43, 0x30, 0x0c, 0x3b, 0x8e, 0x89, 0x1c, 0x68, 0x99, 0x37, 0x3f, 0x58, 0xd4, 0x2c, 0x44, 0x32, 0x22, 0x12, 0xf8, 0x71, 0x5d, 0xde, 0xa3, 0x38, 0x7a, 0x03, 0x1e, 0x56, 0xaf];

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NamedQueryRequest<P> {
    pub contract_lineage: &'static str,
    pub contract_version: u64,
    pub contract_bundle_hash: [u8; 32],
    pub module_hash: [u8; 32],
    pub query_name: &'static str,
    pub parameters: P,
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct QueryResponseIdentity<'a> {
    pub contract_lineage: &'a str,
    pub contract_version: u64,
    pub contract_bundle_hash: [u8; 32],
    pub module_hash: [u8; 32],
    pub query_name: &'a str,
}
impl<P> NamedQueryRequest<P> {
    pub fn accepts_identity(&self, identity: &QueryResponseIdentity<'_>) -> bool {
        identity.contract_lineage == self.contract_lineage
            && identity.contract_version == self.contract_version
            && identity.contract_bundle_hash == self.contract_bundle_hash
            && identity.module_hash == self.module_hash
            && identity.query_name == self.query_name
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommandRequest<I> {
    pub command_name: &'static str,
    pub input: I,
    pub idempotency_key: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetTicketParams {
    pub organization_id: String,
    pub ticket_id: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetTicketFoundTicket {
    pub ticket_id: String,
    pub project_id: String,
    pub title: String,
    pub status: String,
    pub reporter_id: String,
    pub assignee_id: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetTicketFound {
    pub ticket: GetTicketFoundTicket,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetTicketNotFound {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum GetTicketResult {
    Found(Box<GetTicketFound>),
    NotFound(Box<GetTicketNotFound>),
}

pub fn get_ticket(parameters: GetTicketParams) -> NamedQueryRequest<GetTicketParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "GetTicket", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetUserParams {
    pub organization_id: String,
    pub user_id: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetUserFoundUser {
    pub user_id: String,
    pub email: String,
    pub display_name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetUserFound {
    pub user: GetUserFoundUser,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GetUserNotFound {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum GetUserResult {
    Found(Box<GetUserFound>),
    NotFound(Box<GetUserNotFound>),
}

pub fn get_user(parameters: GetUserParams) -> NamedQueryRequest<GetUserParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "GetUser", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListCommentsParams {
    pub organization_id: String,
    pub ticket_id: String,
    pub after: Option<String>,
    pub limit: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListCommentsFoundComments {
    pub comment_id: String,
    pub body: String,
    pub author_id: String,
    pub created_at: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListCommentsFound {
    pub comments: Vec<ListCommentsFoundComments>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ListCommentsResult {
    Found(Box<ListCommentsFound>),
}

pub fn list_comments(parameters: ListCommentsParams) -> NamedQueryRequest<ListCommentsParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "ListComments", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsParams {
    pub organization_id: String,
    pub project_id: String,
    pub statuses: Vec<String>,
    pub after: Option<String>,
    pub limit: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsFoundTickets {
    pub ticket_id: String,
    pub project_id: String,
    pub title: String,
    pub status: String,
    pub updated_at: String,
    pub reporter_id: String,
    pub assignee_id: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsFound {
    pub tickets: Vec<ListTicketsFoundTickets>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ListTicketsResult {
    Found(Box<ListTicketsFound>),
}

pub fn list_tickets(parameters: ListTicketsParams) -> NamedQueryRequest<ListTicketsParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "ListTickets", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsByAssigneeParams {
    pub organization_id: String,
    pub assignee_id: String,
    pub statuses: Vec<String>,
    pub after: Option<String>,
    pub limit: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsByAssigneeFoundTickets {
    pub ticket_id: String,
    pub project_id: String,
    pub title: String,
    pub status: String,
    pub updated_at: String,
    pub reporter_id: String,
    pub assignee_id: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsByAssigneeFound {
    pub tickets: Vec<ListTicketsByAssigneeFoundTickets>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ListTicketsByAssigneeResult {
    Found(Box<ListTicketsByAssigneeFound>),
}

pub fn list_tickets_by_assignee(parameters: ListTicketsByAssigneeParams) -> NamedQueryRequest<ListTicketsByAssigneeParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "ListTicketsByAssignee", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectMembersParams {
    pub organization_id: String,
    pub project_id: String,
    pub after: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectMembersFoundMembers {
    pub user_id: String,
    pub role: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectMembersFound {
    pub members: Vec<ProjectMembersFoundMembers>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProjectMembersResult {
    Found(Box<ProjectMembersFound>),
}

pub fn project_members(parameters: ProjectMembersParams) -> NamedQueryRequest<ProjectMembersParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "ProjectMembers", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryParams {
    pub organization_id: String,
    pub project_id: String,
    pub status: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryFoundProject {
    pub project_id: String,
    pub name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryFoundRecentTickets {
    pub ticket_id: String,
    pub title: String,
    pub status: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryFound {
    pub project: ProjectSummaryFoundProject,
    pub recent_tickets: Vec<ProjectSummaryFoundRecentTickets>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryNotFound {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProjectSummaryResult {
    Found(Box<ProjectSummaryFound>),
    NotFound(Box<ProjectSummaryNotFound>),
}

pub fn project_summary(parameters: ProjectSummaryParams) -> NamedQueryRequest<ProjectSummaryParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "ProjectSummary", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageParams {
    pub organization_id: String,
    pub ticket_id: String,
    pub comments_after: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundTicket {
    pub ticket_id: String,
    pub project_id: String,
    pub title: String,
    pub status: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundProject {
    pub project_id: String,
    pub name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundOrganization {
    pub organization_id: String,
    pub name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundReporter {
    pub user_id: String,
    pub display_name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundAssignee {
    pub user_id: String,
    pub display_name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundComments {
    pub comment_id: String,
    pub body: String,
    pub author_id: String,
    pub created_at: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundLabels {
    pub label_id: String,
    pub name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFound {
    pub ticket: TicketPageFoundTicket,
    pub project: TicketPageFoundProject,
    pub organization: TicketPageFoundOrganization,
    pub reporter: TicketPageFoundReporter,
    pub assignee: Option<TicketPageFoundAssignee>,
    pub comments: Vec<TicketPageFoundComments>,
    pub labels: Vec<TicketPageFoundLabels>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageNotFound {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageIntegrityFailure {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TicketPageResult {
    Found(Box<TicketPageFound>),
    NotFound(Box<TicketPageNotFound>),
    IntegrityFailure(Box<TicketPageIntegrityFailure>),
}

pub fn ticket_page(parameters: TicketPageParams) -> NamedQueryRequest<TicketPageParams> {
    NamedQueryRequest { contract_lineage: CONTRACT_LINEAGE, contract_version: CONTRACT_VERSION, contract_bundle_hash: CONTRACT_BUNDLE_HASH, module_hash: QUERY_MODULE_HASH, query_name: "TicketPage", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AddProjectMemberInput {
    pub role: String,
    pub user_id: String,
    pub project_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn add_project_member(input: AddProjectMemberInput, idempotency_key: String) -> CommandRequest<AddProjectMemberInput> {
    CommandRequest { command_name: "AddProjectMember", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AttachLabelInput {
    pub label_id: String,
    pub ticket_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn attach_label(input: AttachLabelInput, idempotency_key: String) -> CommandRequest<AttachLabelInput> {
    CommandRequest { command_name: "AttachLabel", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateCommentInput {
    pub body: String,
    pub author_id: String,
    pub ticket_id: String,
    pub comment_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_comment(input: CreateCommentInput, idempotency_key: String) -> CommandRequest<CreateCommentInput> {
    CommandRequest { command_name: "CreateComment", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateLabelInput {
    pub name: String,
    pub label_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_label(input: CreateLabelInput, idempotency_key: String) -> CommandRequest<CreateLabelInput> {
    CommandRequest { command_name: "CreateLabel", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateOrganizationInput {
    pub name: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_organization(input: CreateOrganizationInput, idempotency_key: String) -> CommandRequest<CreateOrganizationInput> {
    CommandRequest { command_name: "CreateOrganization", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateProjectInput {
    pub name: String,
    pub project_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_project(input: CreateProjectInput, idempotency_key: String) -> CommandRequest<CreateProjectInput> {
    CommandRequest { command_name: "CreateProject", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateTicketInput {
    pub title: String,
    pub status: String,
    pub ticket_id: String,
    pub project_id: String,
    pub assignee_id: String,
    pub reporter_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_ticket(input: CreateTicketInput, idempotency_key: String) -> CommandRequest<CreateTicketInput> {
    CommandRequest { command_name: "CreateTicket", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateUserInput {
    pub email: String,
    pub user_id: String,
    pub display_name: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_user(input: CreateUserInput, idempotency_key: String) -> CommandRequest<CreateUserInput> {
    CommandRequest { command_name: "CreateUser", input, idempotency_key }
}

