// @generated by riffdb-query-module; do not edit.

pub const QUERY_MODULE_HASH: [u8; 32] = [0xf8, 0x83, 0xbe, 0xad, 0x2d, 0x14, 0xe4, 0xc7, 0xf7, 0x38, 0xed, 0x9a, 0xf3, 0x81, 0x01, 0x8d, 0xcc, 0x66, 0xc7, 0x6b, 0x6e, 0xf3, 0x5b, 0x82, 0x65, 0xdb, 0x7b, 0x26, 0x32, 0x7c, 0xba, 0x92];
pub const CONTRACT_LINEAGE: &str = "TicketDesk";
pub const CONTRACT_VERSION: u64 = 1;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NamedQueryRequest<P> {
    pub module_hash: [u8; 32],
    pub query_name: &'static str,
    pub parameters: P,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommandRequest<I> {
    pub command_name: &'static str,
    pub input: I,
    pub idempotency_key: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsParams {
    pub organization_id: String,
    pub project_id: String,
    pub statuses: Vec<String>,
    pub after: Option<String>,
    pub limit: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsFoundTickets {
    pub ticket_id: String,
    pub title: String,
    pub status: String,
    pub updated_at: String,
    pub reporter_id: String,
    pub assignee_id: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListTicketsFound {
    pub tickets: Vec<ListTicketsFoundTickets>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ListTicketsResult {
    Found(ListTicketsFound),
}

pub fn list_tickets(parameters: ListTicketsParams) -> NamedQueryRequest<ListTicketsParams> {
    NamedQueryRequest { module_hash: QUERY_MODULE_HASH, query_name: "ListTickets", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectMembersParams {
    pub organization_id: String,
    pub project_id: String,
    pub after: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectMembersFoundMembers {
    pub user_id: String,
    pub role: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectMembersFound {
    pub members: Vec<ProjectMembersFoundMembers>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProjectMembersResult {
    Found(ProjectMembersFound),
}

pub fn project_members(parameters: ProjectMembersParams) -> NamedQueryRequest<ProjectMembersParams> {
    NamedQueryRequest { module_hash: QUERY_MODULE_HASH, query_name: "ProjectMembers", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryParams {
    pub organization_id: String,
    pub project_id: String,
    pub status: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryFoundProject {
    pub project_id: String,
    pub name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryFoundRecentTickets {
    pub ticket_id: String,
    pub title: String,
    pub status: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryFound {
    pub project: ProjectSummaryFoundProject,
    pub recent_tickets: Vec<ProjectSummaryFoundRecentTickets>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSummaryNotFound {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProjectSummaryResult {
    Found(ProjectSummaryFound),
    NotFound(ProjectSummaryNotFound),
}

pub fn project_summary(parameters: ProjectSummaryParams) -> NamedQueryRequest<ProjectSummaryParams> {
    NamedQueryRequest { module_hash: QUERY_MODULE_HASH, query_name: "ProjectSummary", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageParams {
    pub organization_id: String,
    pub ticket_id: String,
    pub comments_after: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundTicket {
    pub ticket_id: String,
    pub title: String,
    pub status: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundReporter {
    pub user_id: String,
    pub display_name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundAssignee {
    pub user_id: String,
    pub display_name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFoundComments {
    pub comment_id: String,
    pub body: String,
    pub author_id: String,
    pub created_at: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageFound {
    pub ticket: TicketPageFoundTicket,
    pub reporter: TicketPageFoundReporter,
    pub assignee: Option<TicketPageFoundAssignee>,
    pub comments: Vec<TicketPageFoundComments>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageNotFound {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TicketPageIntegrityFailure {
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TicketPageResult {
    Found(TicketPageFound),
    NotFound(TicketPageNotFound),
    IntegrityFailure(TicketPageIntegrityFailure),
}

pub fn ticket_page(parameters: TicketPageParams) -> NamedQueryRequest<TicketPageParams> {
    NamedQueryRequest { module_hash: QUERY_MODULE_HASH, query_name: "TicketPage", parameters }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AddProjectMemberInput {
    pub role: String,
    pub user_id: String,
    pub project_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn add_project_member(input: AddProjectMemberInput, idempotency_key: String) -> CommandRequest<AddProjectMemberInput> {
    CommandRequest { command_name: "AddProjectMember", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AttachLabelInput {
    pub label_id: String,
    pub ticket_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn attach_label(input: AttachLabelInput, idempotency_key: String) -> CommandRequest<AttachLabelInput> {
    CommandRequest { command_name: "AttachLabel", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateCommentInput {
    pub body: String,
    pub author_id: String,
    pub ticket_id: String,
    pub comment_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_comment(input: CreateCommentInput, idempotency_key: String) -> CommandRequest<CreateCommentInput> {
    CommandRequest { command_name: "CreateComment", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateLabelInput {
    pub name: String,
    pub label_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_label(input: CreateLabelInput, idempotency_key: String) -> CommandRequest<CreateLabelInput> {
    CommandRequest { command_name: "CreateLabel", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateOrganizationInput {
    pub name: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_organization(input: CreateOrganizationInput, idempotency_key: String) -> CommandRequest<CreateOrganizationInput> {
    CommandRequest { command_name: "CreateOrganization", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateProjectInput {
    pub name: String,
    pub project_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_project(input: CreateProjectInput, idempotency_key: String) -> CommandRequest<CreateProjectInput> {
    CommandRequest { command_name: "CreateProject", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateTicketInput {
    pub title: String,
    pub status: String,
    pub ticket_id: String,
    pub project_id: String,
    pub assignee_id: String,
    pub reporter_id: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_ticket(input: CreateTicketInput, idempotency_key: String) -> CommandRequest<CreateTicketInput> {
    CommandRequest { command_name: "CreateTicket", input, idempotency_key }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateUserInput {
    pub email: String,
    pub user_id: String,
    pub display_name: String,
    pub idempotency_key: String,
    pub organization_id: String,
}

pub fn create_user(input: CreateUserInput, idempotency_key: String) -> CommandRequest<CreateUserInput> {
    CommandRequest { command_name: "CreateUser", input, idempotency_key }
}

