[package]
name = "riffdb-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
redb = { version = "=4.1.0", default-features = false }
riffdb-storage-redb = { version = "0.1.0", path = "../riffdb-storage-redb", default-features = false }

[dev-dependencies]
riffdb-catalog = { version = "0.1.0", path = "../riffdb-catalog", default-features = false }
riffdb-contract-compiler = { version = "0.1.0", path = "../riffdb-contract-compiler", default-features = false }
riffdb-storage-api = { version = "0.1.0", path = "../riffdb-storage-api" }
riffdb-types = { version = "0.1.0", path = "../riffdb-types" }
serde_json = { version = "=1.0.150", default-features = false, features = ["std"] }

[lints]
workspace = true
